-- fundiOps: WhatsApp Business AI CRM
-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ────────────────────────────────────────────────────────────
-- ENUMS
-- ────────────────────────────────────────────────────────────

CREATE TYPE lead_stage AS ENUM (
  'new', 'contacted', 'warm', 'hot', 'closed_won', 'closed_lost'
);

CREATE TYPE conversation_type AS ENUM (
  'new_lead', 'existing_customer', 'support', 'spam', 'unknown'
);

CREATE TYPE message_direction AS ENUM ('inbound', 'outbound');

CREATE TYPE follow_up_status AS ENUM ('pending', 'sent', 'dismissed');

CREATE TYPE urgency_level AS ENUM ('low', 'medium', 'high');

-- ────────────────────────────────────────────────────────────
-- PROFILES (one per Supabase auth user / business owner)
-- ────────────────────────────────────────────────────────────

CREATE TABLE profiles (
  id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email        TEXT,
  display_name TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────
-- WA_CONTACTS
-- One row per unique WhatsApp phone number per user
-- ────────────────────────────────────────────────────────────

CREATE TABLE wa_contacts (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id          UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  wa_id            TEXT NOT NULL,
  phone            TEXT NOT NULL,
  display_name     TEXT,
  business_name    TEXT,
  email            TEXT,
  interest_summary TEXT,
  urgency          urgency_level,
  tags             TEXT[] NOT NULL DEFAULT '{}',
  auto_reply       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, wa_id)
);

CREATE INDEX wa_contacts_user_created_idx ON wa_contacts(user_id, created_at DESC);

-- ────────────────────────────────────────────────────────────
-- WA_MESSAGES
-- Full conversation log (inbound + outbound)
-- ────────────────────────────────────────────────────────────

CREATE TABLE wa_messages (
  id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id          UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  contact_id       UUID NOT NULL REFERENCES wa_contacts(id) ON DELETE CASCADE,
  wa_message_id    TEXT UNIQUE,
  direction        message_direction NOT NULL,
  body             TEXT NOT NULL,
  media_type       TEXT DEFAULT 'text',
  media_url        TEXT,
  is_ai_generated  BOOLEAN NOT NULL DEFAULT FALSE,
  processed        BOOLEAN NOT NULL DEFAULT FALSE,
  processing_error TEXT,
  received_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX wa_messages_contact_received_idx ON wa_messages(contact_id, received_at DESC);
CREATE INDEX wa_messages_user_received_idx    ON wa_messages(user_id, received_at DESC);
CREATE INDEX wa_messages_unprocessed_idx      ON wa_messages(user_id) WHERE processed = FALSE;

-- ────────────────────────────────────────────────────────────
-- CRM_LEADS
-- One pipeline record per contact (tracks stage, AI notes)
-- ────────────────────────────────────────────────────────────

CREATE TABLE crm_leads (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id         UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  contact_id      UUID NOT NULL REFERENCES wa_contacts(id) ON DELETE CASCADE,
  stage           lead_stage NOT NULL DEFAULT 'new',
  conv_type       conversation_type NOT NULL DEFAULT 'unknown',
  ai_summary      TEXT,
  ai_next_action  TEXT,
  value_estimate  NUMERIC(12,2),
  notes           TEXT,
  closed_at       TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, contact_id)
);

CREATE INDEX crm_leads_user_stage_idx   ON crm_leads(user_id, stage);
CREATE INDEX crm_leads_user_created_idx ON crm_leads(user_id, created_at DESC);

-- ────────────────────────────────────────────────────────────
-- CRM_FOLLOW_UPS
-- Scheduled reminders generated by the AI agent
-- ────────────────────────────────────────────────────────────

CREATE TABLE crm_follow_ups (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id       UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  contact_id    UUID NOT NULL REFERENCES wa_contacts(id) ON DELETE CASCADE,
  lead_id       UUID REFERENCES crm_leads(id) ON DELETE SET NULL,
  message_id    UUID REFERENCES wa_messages(id) ON DELETE SET NULL,
  due_at        TIMESTAMPTZ NOT NULL,
  note          TEXT NOT NULL,
  status        follow_up_status NOT NULL DEFAULT 'pending',
  reminder_sent BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX crm_follow_ups_user_due_idx
  ON crm_follow_ups(user_id, due_at ASC)
  WHERE status = 'pending';

-- ────────────────────────────────────────────────────────────
-- CRM_SETTINGS
-- Per-user global CRM configuration
-- ────────────────────────────────────────────────────────────

CREATE TABLE crm_settings (
  user_id           UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  auto_reply_global BOOLEAN NOT NULL DEFAULT FALSE,
  greeting_template TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ────────────────────────────────────────────────────────────
-- UPDATED_AT TRIGGER
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER wa_contacts_updated_at
  BEFORE UPDATE ON wa_contacts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER crm_leads_updated_at
  BEFORE UPDATE ON crm_leads
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER crm_follow_ups_updated_at
  BEFORE UPDATE ON crm_follow_ups
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER crm_settings_updated_at
  BEFORE UPDATE ON crm_settings
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- ────────────────────────────────────────────────────────────

ALTER TABLE profiles       ENABLE ROW LEVEL SECURITY;
ALTER TABLE wa_contacts    ENABLE ROW LEVEL SECURITY;
ALTER TABLE wa_messages    ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_leads      ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_follow_ups ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_settings   ENABLE ROW LEVEL SECURITY;

CREATE POLICY "profiles_self"       ON profiles       FOR ALL USING (id = auth.uid());
CREATE POLICY "wa_contacts_self"    ON wa_contacts    FOR ALL USING (user_id = auth.uid());
CREATE POLICY "wa_messages_self"    ON wa_messages    FOR ALL USING (user_id = auth.uid());
CREATE POLICY "crm_leads_self"      ON crm_leads      FOR ALL USING (user_id = auth.uid());
CREATE POLICY "crm_follow_ups_self" ON crm_follow_ups FOR ALL USING (user_id = auth.uid());
CREATE POLICY "crm_settings_self"   ON crm_settings   FOR ALL USING (user_id = auth.uid());

-- ────────────────────────────────────────────────────────────
-- HELPER: get pending follow-ups due before a timestamp
-- Used by the hourly cron job
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION get_pending_follow_ups(p_before TIMESTAMPTZ)
RETURNS TABLE (
  id         UUID,
  user_id    UUID,
  contact_id UUID,
  lead_id    UUID,
  note       TEXT,
  due_at     TIMESTAMPTZ
)
LANGUAGE SQL STABLE SECURITY DEFINER AS $$
  SELECT
    f.id, f.user_id, f.contact_id, f.lead_id, f.note, f.due_at
  FROM crm_follow_ups f
  WHERE f.status      = 'pending'
    AND f.reminder_sent = FALSE
    AND f.due_at       <= p_before
  ORDER BY f.due_at ASC
  LIMIT 100;
$$;

-- ────────────────────────────────────────────────────────────
-- AUTO-CREATE profile row on new user signup
-- ────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO profiles (id, email)
  VALUES (NEW.id, NEW.email)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();
