// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hotspot.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activatePurchase = `-- name: ActivatePurchase :one
UPDATE hotspot_purchases SET starts_at = $2, expires_at = $3, mpesa_receipt_number = $4 WHERE id = $1 RETURNING id, tenant_id, router_id, plan_id, source, phone_number, mpesa_receipt_number, voucher_id, macs, max_devices, starts_at, expires_at, expiry_sms_sent_at, created_at
`

type ActivatePurchaseParams struct {
	ID                 uuid.UUID  `json:"id"`
	StartsAt           *time.Time `json:"starts_at"`
	ExpiresAt          *time.Time `json:"expires_at"`
	MpesaReceiptNumber *string    `json:"mpesa_receipt_number"`
}

func (q *Queries) ActivatePurchase(ctx context.Context, arg ActivatePurchaseParams) (HotspotPurchase, error) {
	row := q.db.QueryRow(ctx, activatePurchase,
		arg.ID,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.MpesaReceiptNumber,
	)
	var i HotspotPurchase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.PlanID,
		&i.Source,
		&i.PhoneNumber,
		&i.MpesaReceiptNumber,
		&i.VoucherID,
		&i.Macs,
		&i.MaxDevices,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ExpirySmsSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const activePurchaseForMAC = `-- name: ActivePurchaseForMAC :one
SELECT h.id, h.tenant_id, h.router_id, h.plan_id, h.source, h.phone_number, h.mpesa_receipt_number, h.voucher_id, h.macs, h.max_devices, h.starts_at, h.expires_at, h.expiry_sms_sent_at, h.created_at, p.bandwidth_down_kbps, p.bandwidth_up_kbps, p.data_cap_mb
FROM hotspot_purchases h JOIN plans p ON p.id = h.plan_id
WHERE $1::text = ANY (h.macs) AND h.starts_at IS NOT NULL AND h.expires_at > NOW()
ORDER BY h.expires_at DESC LIMIT 1
`

type ActivePurchaseForMACRow struct {
	ID                 uuid.UUID  `json:"id"`
	TenantID           uuid.UUID  `json:"tenant_id"`
	RouterID           *uuid.UUID `json:"router_id"`
	PlanID             uuid.UUID  `json:"plan_id"`
	Source             string     `json:"source"`
	PhoneNumber        *string    `json:"phone_number"`
	MpesaReceiptNumber *string    `json:"mpesa_receipt_number"`
	VoucherID          *uuid.UUID `json:"voucher_id"`
	Macs               []string   `json:"macs"`
	MaxDevices         int32      `json:"max_devices"`
	StartsAt           *time.Time `json:"starts_at"`
	ExpiresAt          *time.Time `json:"expires_at"`
	ExpirySmsSentAt    *time.Time `json:"expiry_sms_sent_at"`
	CreatedAt          time.Time  `json:"created_at"`
	BandwidthDownKbps  int32      `json:"bandwidth_down_kbps"`
	BandwidthUpKbps    int32      `json:"bandwidth_up_kbps"`
	DataCapMb          *int64     `json:"data_cap_mb"`
}

func (q *Queries) ActivePurchaseForMAC(ctx context.Context, mac string) (ActivePurchaseForMACRow, error) {
	row := q.db.QueryRow(ctx, activePurchaseForMAC, mac)
	var i ActivePurchaseForMACRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.PlanID,
		&i.Source,
		&i.PhoneNumber,
		&i.MpesaReceiptNumber,
		&i.VoucherID,
		&i.Macs,
		&i.MaxDevices,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ExpirySmsSentAt,
		&i.CreatedAt,
		&i.BandwidthDownKbps,
		&i.BandwidthUpKbps,
		&i.DataCapMb,
	)
	return i, err
}

const addPurchaseMAC = `-- name: AddPurchaseMAC :one
UPDATE hotspot_purchases SET macs = array_append(macs, $1::text)
WHERE id = $2 AND NOT ($1::text = ANY (macs)) AND cardinality(macs) < max_devices
RETURNING id, tenant_id, router_id, plan_id, source, phone_number, mpesa_receipt_number, voucher_id, macs, max_devices, starts_at, expires_at, expiry_sms_sent_at, created_at
`

type AddPurchaseMACParams struct {
	Mac string    `json:"mac"`
	ID  uuid.UUID `json:"id"`
}

func (q *Queries) AddPurchaseMAC(ctx context.Context, arg AddPurchaseMACParams) (HotspotPurchase, error) {
	row := q.db.QueryRow(ctx, addPurchaseMAC, arg.Mac, arg.ID)
	var i HotspotPurchase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.PlanID,
		&i.Source,
		&i.PhoneNumber,
		&i.MpesaReceiptNumber,
		&i.VoucherID,
		&i.Macs,
		&i.MaxDevices,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ExpirySmsSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO hotspot_purchases (tenant_id, router_id, plan_id, source, phone_number, voucher_id, macs, max_devices, starts_at, expires_at)
VALUES (app_tenant(), $1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, router_id, plan_id, source, phone_number, mpesa_receipt_number, voucher_id, macs, max_devices, starts_at, expires_at, expiry_sms_sent_at, created_at
`

type CreatePurchaseParams struct {
	RouterID    *uuid.UUID `json:"router_id"`
	PlanID      uuid.UUID  `json:"plan_id"`
	Source      string     `json:"source"`
	PhoneNumber *string    `json:"phone_number"`
	VoucherID   *uuid.UUID `json:"voucher_id"`
	Macs        []string   `json:"macs"`
	MaxDevices  int32      `json:"max_devices"`
	StartsAt    *time.Time `json:"starts_at"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (HotspotPurchase, error) {
	row := q.db.QueryRow(ctx, createPurchase,
		arg.RouterID,
		arg.PlanID,
		arg.Source,
		arg.PhoneNumber,
		arg.VoucherID,
		arg.Macs,
		arg.MaxDevices,
		arg.StartsAt,
		arg.ExpiresAt,
	)
	var i HotspotPurchase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.PlanID,
		&i.Source,
		&i.PhoneNumber,
		&i.MpesaReceiptNumber,
		&i.VoucherID,
		&i.Macs,
		&i.MaxDevices,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ExpirySmsSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const createVoucher = `-- name: CreateVoucher :one
INSERT INTO vouchers (tenant_id, plan_id, code, batch) VALUES (app_tenant(), $1, $2, $3) RETURNING id, tenant_id, plan_id, code, batch, redeemed_at, redeemed_mac, created_at
`

type CreateVoucherParams struct {
	PlanID uuid.UUID `json:"plan_id"`
	Code   string    `json:"code"`
	Batch  *string   `json:"batch"`
}

func (q *Queries) CreateVoucher(ctx context.Context, arg CreateVoucherParams) (Voucher, error) {
	row := q.db.QueryRow(ctx, createVoucher, arg.PlanID, arg.Code, arg.Batch)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Code,
		&i.Batch,
		&i.RedeemedAt,
		&i.RedeemedMac,
		&i.CreatedAt,
	)
	return i, err
}

const getPurchase = `-- name: GetPurchase :one
SELECT id, tenant_id, router_id, plan_id, source, phone_number, mpesa_receipt_number, voucher_id, macs, max_devices, starts_at, expires_at, expiry_sms_sent_at, created_at FROM hotspot_purchases WHERE id = $1
`

func (q *Queries) GetPurchase(ctx context.Context, id uuid.UUID) (HotspotPurchase, error) {
	row := q.db.QueryRow(ctx, getPurchase, id)
	var i HotspotPurchase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.PlanID,
		&i.Source,
		&i.PhoneNumber,
		&i.MpesaReceiptNumber,
		&i.VoucherID,
		&i.Macs,
		&i.MaxDevices,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ExpirySmsSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVoucherByCodeForUpdate = `-- name: GetVoucherByCodeForUpdate :one
SELECT id, tenant_id, plan_id, code, batch, redeemed_at, redeemed_mac, created_at FROM vouchers WHERE code = $1 FOR UPDATE
`

func (q *Queries) GetVoucherByCodeForUpdate(ctx context.Context, code string) (Voucher, error) {
	row := q.db.QueryRow(ctx, getVoucherByCodeForUpdate, code)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Code,
		&i.Batch,
		&i.RedeemedAt,
		&i.RedeemedMac,
		&i.CreatedAt,
	)
	return i, err
}

const hotspotSalesSince = `-- name: HotspotSalesSince :one
SELECT count(*)::int FROM hotspot_purchases WHERE source = 'mpesa' AND starts_at >= $1::timestamptz AND starts_at < $2::timestamptz
`

type HotspotSalesSinceParams struct {
	Since time.Time `json:"since"`
	Until time.Time `json:"until"`
}

func (q *Queries) HotspotSalesSince(ctx context.Context, arg HotspotSalesSinceParams) (int32, error) {
	row := q.db.QueryRow(ctx, hotspotSalesSince, arg.Since, arg.Until)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listExpiryNotices = `-- name: ListExpiryNotices :many
SELECT h.id, h.tenant_id, h.router_id, h.plan_id, h.source, h.phone_number, h.mpesa_receipt_number, h.voucher_id, h.macs, h.max_devices, h.starts_at, h.expires_at, h.expiry_sms_sent_at, h.created_at, p.name AS plan_name FROM hotspot_purchases h JOIN plans p ON p.id = h.plan_id
WHERE h.source = 'mpesa' AND h.phone_number IS NOT NULL AND h.expires_at <= NOW()
  AND h.expires_at > NOW() - INTERVAL '1 day' AND h.expiry_sms_sent_at IS NULL
`

type ListExpiryNoticesRow struct {
	ID                 uuid.UUID  `json:"id"`
	TenantID           uuid.UUID  `json:"tenant_id"`
	RouterID           *uuid.UUID `json:"router_id"`
	PlanID             uuid.UUID  `json:"plan_id"`
	Source             string     `json:"source"`
	PhoneNumber        *string    `json:"phone_number"`
	MpesaReceiptNumber *string    `json:"mpesa_receipt_number"`
	VoucherID          *uuid.UUID `json:"voucher_id"`
	Macs               []string   `json:"macs"`
	MaxDevices         int32      `json:"max_devices"`
	StartsAt           *time.Time `json:"starts_at"`
	ExpiresAt          *time.Time `json:"expires_at"`
	ExpirySmsSentAt    *time.Time `json:"expiry_sms_sent_at"`
	CreatedAt          time.Time  `json:"created_at"`
	PlanName           string     `json:"plan_name"`
}

func (q *Queries) ListExpiryNotices(ctx context.Context) ([]ListExpiryNoticesRow, error) {
	rows, err := q.db.Query(ctx, listExpiryNotices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiryNoticesRow{}
	for rows.Next() {
		var i ListExpiryNoticesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RouterID,
			&i.PlanID,
			&i.Source,
			&i.PhoneNumber,
			&i.MpesaReceiptNumber,
			&i.VoucherID,
			&i.Macs,
			&i.MaxDevices,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.ExpirySmsSentAt,
			&i.CreatedAt,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVouchers = `-- name: ListVouchers :many
SELECT v.id, v.tenant_id, v.plan_id, v.code, v.batch, v.redeemed_at, v.redeemed_mac, v.created_at, p.name AS plan_name FROM vouchers v JOIN plans p ON p.id = v.plan_id
WHERE ($2::text IS NULL OR v.batch = $2::text)
ORDER BY v.created_at DESC LIMIT $1
`

type ListVouchersParams struct {
	Limit int32   `json:"limit"`
	Batch *string `json:"batch"`
}

type ListVouchersRow struct {
	ID          uuid.UUID  `json:"id"`
	TenantID    uuid.UUID  `json:"tenant_id"`
	PlanID      uuid.UUID  `json:"plan_id"`
	Code        string     `json:"code"`
	Batch       *string    `json:"batch"`
	RedeemedAt  *time.Time `json:"redeemed_at"`
	RedeemedMac *string    `json:"redeemed_mac"`
	CreatedAt   time.Time  `json:"created_at"`
	PlanName    string     `json:"plan_name"`
}

func (q *Queries) ListVouchers(ctx context.Context, arg ListVouchersParams) ([]ListVouchersRow, error) {
	rows, err := q.db.Query(ctx, listVouchers, arg.Limit, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVouchersRow{}
	for rows.Next() {
		var i ListVouchersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PlanID,
			&i.Code,
			&i.Batch,
			&i.RedeemedAt,
			&i.RedeemedMac,
			&i.CreatedAt,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpirySMSSent = `-- name: MarkExpirySMSSent :exec
UPDATE hotspot_purchases SET expiry_sms_sent_at = NOW() WHERE id = $1
`

func (q *Queries) MarkExpirySMSSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markExpirySMSSent, id)
	return err
}

const purchaseByReceiptForUpdate = `-- name: PurchaseByReceiptForUpdate :one
SELECT id, tenant_id, router_id, plan_id, source, phone_number, mpesa_receipt_number, voucher_id, macs, max_devices, starts_at, expires_at, expiry_sms_sent_at, created_at FROM hotspot_purchases WHERE mpesa_receipt_number = upper(trim($1::text)) FOR UPDATE
`

func (q *Queries) PurchaseByReceiptForUpdate(ctx context.Context, receipt string) (HotspotPurchase, error) {
	row := q.db.QueryRow(ctx, purchaseByReceiptForUpdate, receipt)
	var i HotspotPurchase
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.PlanID,
		&i.Source,
		&i.PhoneNumber,
		&i.MpesaReceiptNumber,
		&i.VoucherID,
		&i.Macs,
		&i.MaxDevices,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ExpirySmsSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const redeemVoucher = `-- name: RedeemVoucher :exec
UPDATE vouchers SET redeemed_at = NOW(), redeemed_mac = $2 WHERE id = $1
`

type RedeemVoucherParams struct {
	ID          uuid.UUID `json:"id"`
	RedeemedMac *string   `json:"redeemed_mac"`
}

func (q *Queries) RedeemVoucher(ctx context.Context, arg RedeemVoucherParams) error {
	_, err := q.db.Exec(ctx, redeemVoucher, arg.ID, arg.RedeemedMac)
	return err
}

const trialUsedSince = `-- name: TrialUsedSince :one
SELECT EXISTS (SELECT 1 FROM hotspot_purchases WHERE source = 'trial' AND $1::text = ANY (macs) AND created_at > $2::timestamptz) AS used
`

type TrialUsedSinceParams struct {
	Mac   string    `json:"mac"`
	Since time.Time `json:"since"`
}

func (q *Queries) TrialUsedSince(ctx context.Context, arg TrialUsedSinceParams) (bool, error) {
	row := q.db.QueryRow(ctx, trialUsedSince, arg.Mac, arg.Since)
	var used bool
	err := row.Scan(&used)
	return used, err
}
