// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AuthSession struct {
	TokenHash []byte    `json:"token_hash"`
	TenantID  uuid.UUID `json:"tenant_id"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type ConfigAudit struct {
	ID           uuid.UUID  `json:"id"`
	TenantID     uuid.UUID  `json:"tenant_id"`
	RouterID     *uuid.UUID `json:"router_id"`
	Action       string     `json:"action"`
	Payload      []byte     `json:"payload"`
	Status       string     `json:"status"`
	ErrorMessage *string    `json:"error_message"`
	InitiatedBy  string     `json:"initiated_by"`
	CreatedAt    time.Time  `json:"created_at"`
}

type HotspotPurchase struct {
	ID                 uuid.UUID  `json:"id"`
	TenantID           uuid.UUID  `json:"tenant_id"`
	RouterID           *uuid.UUID `json:"router_id"`
	PlanID             uuid.UUID  `json:"plan_id"`
	Source             string     `json:"source"`
	PhoneNumber        *string    `json:"phone_number"`
	MpesaReceiptNumber *string    `json:"mpesa_receipt_number"`
	VoucherID          *uuid.UUID `json:"voucher_id"`
	Macs               []string   `json:"macs"`
	MaxDevices         int32      `json:"max_devices"`
	StartsAt           *time.Time `json:"starts_at"`
	ExpiresAt          *time.Time `json:"expires_at"`
	ExpirySmsSentAt    *time.Time `json:"expiry_sms_sent_at"`
	CreatedAt          time.Time  `json:"created_at"`
}

type Location struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Name      string    `json:"name"`
	Address   *string   `json:"address"`
	Lat       *float64  `json:"lat"`
	Lng       *float64  `json:"lng"`
	CreatedAt time.Time `json:"created_at"`
}

type MpesaTransaction struct {
	ID                 uuid.UUID  `json:"id"`
	TenantID           uuid.UUID  `json:"tenant_id"`
	Source             string     `json:"source"`
	Purpose            string     `json:"purpose"`
	MerchantRequestID  *string    `json:"merchant_request_id"`
	CheckoutRequestID  *string    `json:"checkout_request_id"`
	MpesaReceiptNumber *string    `json:"mpesa_receipt_number"`
	PhoneNumber        *string    `json:"phone_number"`
	AmountCents        int32      `json:"amount_cents"`
	AccountReference   string     `json:"account_reference"`
	TransactionDesc    *string    `json:"transaction_desc"`
	Status             string     `json:"status"`
	ResultCode         *int32     `json:"result_code"`
	ResultDesc         *string    `json:"result_desc"`
	CallbackReceivedAt *time.Time `json:"callback_received_at"`
	SubscriberID       *uuid.UUID `json:"subscriber_id"`
	HotspotPurchaseID  *uuid.UUID `json:"hotspot_purchase_id"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
}

type OnboardingToken struct {
	TokenHash []byte     `json:"token_hash"`
	TenantID  uuid.UUID  `json:"tenant_id"`
	RouterID  uuid.UUID  `json:"router_id"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type Plan struct {
	ID                  uuid.UUID  `json:"id"`
	TenantID            uuid.UUID  `json:"tenant_id"`
	LocationID          *uuid.UUID `json:"location_id"`
	Name                string     `json:"name"`
	AccessType          string     `json:"access_type"`
	PriceCents          int32      `json:"price_cents"`
	Currency            string     `json:"currency"`
	DurationDays        *int32     `json:"duration_days"`
	DurationMinutes     *int32     `json:"duration_minutes"`
	IsTrial             bool       `json:"is_trial"`
	DataCapMb           *int64     `json:"data_cap_mb"`
	BandwidthDownKbps   int32      `json:"bandwidth_down_kbps"`
	BandwidthUpKbps     int32      `json:"bandwidth_up_kbps"`
	MaxDevices          int32      `json:"max_devices"`
	MikrotikProfileName *string    `json:"mikrotik_profile_name"`
	IsActive            bool       `json:"is_active"`
	SortOrder           int32      `json:"sort_order"`
	CreatedAt           time.Time  `json:"created_at"`
}

type Router struct {
	ID              uuid.UUID  `json:"id"`
	TenantID        uuid.UUID  `json:"tenant_id"`
	LocationID      uuid.UUID  `json:"location_id"`
	Name            string     `json:"name"`
	SerialNumber    *string    `json:"serial_number"`
	BoardName       *string    `json:"board_name"`
	Architecture    *string    `json:"architecture"`
	FirmwareVersion *string    `json:"firmware_version"`
	TunnelIp        netip.Addr `json:"tunnel_ip"`
	WgPublicKey     *string    `json:"wg_public_key"`
	ApiUser         string     `json:"api_user"`
	ApiPasswordEnc  []byte     `json:"api_password_enc"`
	HotspotPorts    []string   `json:"hotspot_ports"`
	PppoePorts      []string   `json:"pppoe_ports"`
	Status          string     `json:"status"`
	MissedPolls     int32      `json:"missed_polls"`
	LastSeenAt      *time.Time `json:"last_seen_at"`
	StatusChangedAt time.Time  `json:"status_changed_at"`
	LastConfigPush  *time.Time `json:"last_config_push"`
	ConfigHash      *string    `json:"config_hash"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type Session struct {
	ID               uuid.UUID   `json:"id"`
	TenantID         uuid.UUID   `json:"tenant_id"`
	RouterID         uuid.UUID   `json:"router_id"`
	PlanID           *uuid.UUID  `json:"plan_id"`
	AccessType       string      `json:"access_type"`
	Username         string      `json:"username"`
	AcctSessionID    string      `json:"acct_session_id"`
	MacAddress       *string     `json:"mac_address"`
	IpAddress        *netip.Addr `json:"ip_address"`
	Status           string      `json:"status"`
	StartedAt        time.Time   `json:"started_at"`
	TerminatedAt     *time.Time  `json:"terminated_at"`
	TerminationCause *string     `json:"termination_cause"`
	BytesIn          int64       `json:"bytes_in"`
	BytesOut         int64       `json:"bytes_out"`
	SessionTimeSec   int32       `json:"session_time_sec"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type SmsMessage struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	ToNumber     string    `json:"to_number"`
	Body         string    `json:"body"`
	Kind         string    `json:"kind"`
	Status       string    `json:"status"`
	Credits      int32     `json:"credits"`
	ProviderID   *string   `json:"provider_id"`
	ErrorMessage *string   `json:"error_message"`
	CreatedAt    time.Time `json:"created_at"`
}

type Subscriber struct {
	ID               uuid.UUID  `json:"id"`
	TenantID         uuid.UUID  `json:"tenant_id"`
	LocationID       *uuid.UUID `json:"location_id"`
	FullName         string     `json:"full_name"`
	PhoneNumber      string     `json:"phone_number"`
	Email            *string    `json:"email"`
	PhysicalAddress  *string    `json:"physical_address"`
	PppoeUsername    string     `json:"pppoe_username"`
	PppoePasswordEnc []byte     `json:"pppoe_password_enc"`
	Status           string     `json:"status"`
	PlanID           *uuid.UUID `json:"plan_id"`
	NextRenewalAt    *time.Time `json:"next_renewal_at"`
	CreditCents      int32      `json:"credit_cents"`
	AutoRenew        bool       `json:"auto_renew"`
	ReminderStage    int32      `json:"reminder_stage"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type Tenant struct {
	ID                       uuid.UUID  `json:"id"`
	Email                    string     `json:"email"`
	PasswordHash             string     `json:"password_hash"`
	Name                     string     `json:"name"`
	Slug                     string     `json:"slug"`
	AccountPrefix            string     `json:"account_prefix"`
	NextAccountNo            int32      `json:"next_account_no"`
	Plan                     string     `json:"plan"`
	MpesaMode                string     `json:"mpesa_mode"`
	MpesaShortcodeType       string     `json:"mpesa_shortcode_type"`
	MpesaShortcode           *string    `json:"mpesa_shortcode"`
	MpesaStoreNumber         *string    `json:"mpesa_store_number"`
	MpesaCredentialsEnc      []byte     `json:"mpesa_credentials_enc"`
	MpesaEnv                 string     `json:"mpesa_env"`
	CallbackToken            string     `json:"callback_token"`
	DekWrapped               []byte     `json:"dek_wrapped"`
	SmsCredits               int32      `json:"sms_credits"`
	SmsSender                *string    `json:"sms_sender"`
	ReminderSmsEnabled       bool       `json:"reminder_sms_enabled"`
	HotspotExpirySmsEnabled  bool       `json:"hotspot_expiry_sms_enabled"`
	HotspotExpirySmsTemplate *string    `json:"hotspot_expiry_sms_template"`
	SupportPhone             *string    `json:"support_phone"`
	SubscriptionStatus       string     `json:"subscription_status"`
	TrialEndsAt              time.Time  `json:"trial_ends_at"`
	SubscriptionExpiresAt    *time.Time `json:"subscription_expires_at"`
	GraceHours               int32      `json:"grace_hours"`
	PortalDomain             *string    `json:"portal_domain"`
	LogoUrl                  *string    `json:"logo_url"`
	PrimaryColor             string     `json:"primary_color"`
	Timezone                 string     `json:"timezone"`
	CreatedAt                time.Time  `json:"created_at"`
	UpdatedAt                time.Time  `json:"updated_at"`
}

type Voucher struct {
	ID          uuid.UUID  `json:"id"`
	TenantID    uuid.UUID  `json:"tenant_id"`
	PlanID      uuid.UUID  `json:"plan_id"`
	Code        string     `json:"code"`
	Batch       *string    `json:"batch"`
	RedeemedAt  *time.Time `json:"redeemed_at"`
	RedeemedMac *string    `json:"redeemed_mac"`
	CreatedAt   time.Time  `json:"created_at"`
}
