// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: mpesa.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeTx = `-- name: CompleteTx :exec
UPDATE mpesa_transactions SET status = $2, result_code = $3, result_desc = $4, mpesa_receipt_number = $5,
    amount_cents = COALESCE($6::int, amount_cents), callback_received_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type CompleteTxParams struct {
	ID                 uuid.UUID `json:"id"`
	Status             string    `json:"status"`
	ResultCode         *int32    `json:"result_code"`
	ResultDesc         *string   `json:"result_desc"`
	MpesaReceiptNumber *string   `json:"mpesa_receipt_number"`
	AmountCents        *int32    `json:"amount_cents"`
}

func (q *Queries) CompleteTx(ctx context.Context, arg CompleteTxParams) error {
	_, err := q.db.Exec(ctx, completeTx,
		arg.ID,
		arg.Status,
		arg.ResultCode,
		arg.ResultDesc,
		arg.MpesaReceiptNumber,
		arg.AmountCents,
	)
	return err
}

const countUnmatched = `-- name: CountUnmatched :one
SELECT count(*)::int FROM mpesa_transactions WHERE status = 'unmatched'
`

func (q *Queries) CountUnmatched(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countUnmatched)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createC2BTransaction = `-- name: CreateC2BTransaction :one
INSERT INTO mpesa_transactions (tenant_id, source, mpesa_receipt_number, phone_number, amount_cents, account_reference,
                                status, subscriber_id, callback_received_at)
VALUES (app_tenant(), 'c2b', $1, $2, $3, $4, $5, $6, NOW())
RETURNING id, tenant_id, source, purpose, merchant_request_id, checkout_request_id, mpesa_receipt_number, phone_number, amount_cents, account_reference, transaction_desc, status, result_code, result_desc, callback_received_at, subscriber_id, hotspot_purchase_id, created_at, updated_at
`

type CreateC2BTransactionParams struct {
	MpesaReceiptNumber *string    `json:"mpesa_receipt_number"`
	PhoneNumber        *string    `json:"phone_number"`
	AmountCents        int32      `json:"amount_cents"`
	AccountReference   string     `json:"account_reference"`
	Status             string     `json:"status"`
	SubscriberID       *uuid.UUID `json:"subscriber_id"`
}

func (q *Queries) CreateC2BTransaction(ctx context.Context, arg CreateC2BTransactionParams) (MpesaTransaction, error) {
	row := q.db.QueryRow(ctx, createC2BTransaction,
		arg.MpesaReceiptNumber,
		arg.PhoneNumber,
		arg.AmountCents,
		arg.AccountReference,
		arg.Status,
		arg.SubscriberID,
	)
	var i MpesaTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Purpose,
		&i.MerchantRequestID,
		&i.CheckoutRequestID,
		&i.MpesaReceiptNumber,
		&i.PhoneNumber,
		&i.AmountCents,
		&i.AccountReference,
		&i.TransactionDesc,
		&i.Status,
		&i.ResultCode,
		&i.ResultDesc,
		&i.CallbackReceivedAt,
		&i.SubscriberID,
		&i.HotspotPurchaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSTKTransaction = `-- name: CreateSTKTransaction :one
INSERT INTO mpesa_transactions (tenant_id, source, purpose, merchant_request_id, checkout_request_id, phone_number,
                                amount_cents, account_reference, transaction_desc, subscriber_id, hotspot_purchase_id)
VALUES (app_tenant(), 'stk', $1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, source, purpose, merchant_request_id, checkout_request_id, mpesa_receipt_number, phone_number, amount_cents, account_reference, transaction_desc, status, result_code, result_desc, callback_received_at, subscriber_id, hotspot_purchase_id, created_at, updated_at
`

type CreateSTKTransactionParams struct {
	Purpose           string     `json:"purpose"`
	MerchantRequestID *string    `json:"merchant_request_id"`
	CheckoutRequestID *string    `json:"checkout_request_id"`
	PhoneNumber       *string    `json:"phone_number"`
	AmountCents       int32      `json:"amount_cents"`
	AccountReference  string     `json:"account_reference"`
	TransactionDesc   *string    `json:"transaction_desc"`
	SubscriberID      *uuid.UUID `json:"subscriber_id"`
	HotspotPurchaseID *uuid.UUID `json:"hotspot_purchase_id"`
}

func (q *Queries) CreateSTKTransaction(ctx context.Context, arg CreateSTKTransactionParams) (MpesaTransaction, error) {
	row := q.db.QueryRow(ctx, createSTKTransaction,
		arg.Purpose,
		arg.MerchantRequestID,
		arg.CheckoutRequestID,
		arg.PhoneNumber,
		arg.AmountCents,
		arg.AccountReference,
		arg.TransactionDesc,
		arg.SubscriberID,
		arg.HotspotPurchaseID,
	)
	var i MpesaTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Purpose,
		&i.MerchantRequestID,
		&i.CheckoutRequestID,
		&i.MpesaReceiptNumber,
		&i.PhoneNumber,
		&i.AmountCents,
		&i.AccountReference,
		&i.TransactionDesc,
		&i.Status,
		&i.ResultCode,
		&i.ResultDesc,
		&i.CallbackReceivedAt,
		&i.SubscriberID,
		&i.HotspotPurchaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTx = `-- name: GetTx :one
SELECT id, tenant_id, source, purpose, merchant_request_id, checkout_request_id, mpesa_receipt_number, phone_number, amount_cents, account_reference, transaction_desc, status, result_code, result_desc, callback_received_at, subscriber_id, hotspot_purchase_id, created_at, updated_at FROM mpesa_transactions WHERE id = $1
`

func (q *Queries) GetTx(ctx context.Context, id uuid.UUID) (MpesaTransaction, error) {
	row := q.db.QueryRow(ctx, getTx, id)
	var i MpesaTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Purpose,
		&i.MerchantRequestID,
		&i.CheckoutRequestID,
		&i.MpesaReceiptNumber,
		&i.PhoneNumber,
		&i.AmountCents,
		&i.AccountReference,
		&i.TransactionDesc,
		&i.Status,
		&i.ResultCode,
		&i.ResultDesc,
		&i.CallbackReceivedAt,
		&i.SubscriberID,
		&i.HotspotPurchaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTxByCheckout = `-- name: GetTxByCheckout :one
SELECT id, tenant_id, source, purpose, merchant_request_id, checkout_request_id, mpesa_receipt_number, phone_number, amount_cents, account_reference, transaction_desc, status, result_code, result_desc, callback_received_at, subscriber_id, hotspot_purchase_id, created_at, updated_at FROM mpesa_transactions WHERE checkout_request_id = $1
`

func (q *Queries) GetTxByCheckout(ctx context.Context, checkoutRequestID *string) (MpesaTransaction, error) {
	row := q.db.QueryRow(ctx, getTxByCheckout, checkoutRequestID)
	var i MpesaTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Purpose,
		&i.MerchantRequestID,
		&i.CheckoutRequestID,
		&i.MpesaReceiptNumber,
		&i.PhoneNumber,
		&i.AmountCents,
		&i.AccountReference,
		&i.TransactionDesc,
		&i.Status,
		&i.ResultCode,
		&i.ResultDesc,
		&i.CallbackReceivedAt,
		&i.SubscriberID,
		&i.HotspotPurchaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTxByCheckoutForUpdate = `-- name: GetTxByCheckoutForUpdate :one
SELECT id, tenant_id, source, purpose, merchant_request_id, checkout_request_id, mpesa_receipt_number, phone_number, amount_cents, account_reference, transaction_desc, status, result_code, result_desc, callback_received_at, subscriber_id, hotspot_purchase_id, created_at, updated_at FROM mpesa_transactions WHERE checkout_request_id = $1 FOR UPDATE
`

func (q *Queries) GetTxByCheckoutForUpdate(ctx context.Context, checkoutRequestID *string) (MpesaTransaction, error) {
	row := q.db.QueryRow(ctx, getTxByCheckoutForUpdate, checkoutRequestID)
	var i MpesaTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Purpose,
		&i.MerchantRequestID,
		&i.CheckoutRequestID,
		&i.MpesaReceiptNumber,
		&i.PhoneNumber,
		&i.AmountCents,
		&i.AccountReference,
		&i.TransactionDesc,
		&i.Status,
		&i.ResultCode,
		&i.ResultDesc,
		&i.CallbackReceivedAt,
		&i.SubscriberID,
		&i.HotspotPurchaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestTxForPurchase = `-- name: LatestTxForPurchase :one
SELECT id, tenant_id, source, purpose, merchant_request_id, checkout_request_id, mpesa_receipt_number, phone_number, amount_cents, account_reference, transaction_desc, status, result_code, result_desc, callback_received_at, subscriber_id, hotspot_purchase_id, created_at, updated_at FROM mpesa_transactions WHERE hotspot_purchase_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LatestTxForPurchase(ctx context.Context, hotspotPurchaseID *uuid.UUID) (MpesaTransaction, error) {
	row := q.db.QueryRow(ctx, latestTxForPurchase, hotspotPurchaseID)
	var i MpesaTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Source,
		&i.Purpose,
		&i.MerchantRequestID,
		&i.CheckoutRequestID,
		&i.MpesaReceiptNumber,
		&i.PhoneNumber,
		&i.AmountCents,
		&i.AccountReference,
		&i.TransactionDesc,
		&i.Status,
		&i.ResultCode,
		&i.ResultDesc,
		&i.CallbackReceivedAt,
		&i.SubscriberID,
		&i.HotspotPurchaseID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT t.id, t.tenant_id, t.source, t.purpose, t.merchant_request_id, t.checkout_request_id, t.mpesa_receipt_number, t.phone_number, t.amount_cents, t.account_reference, t.transaction_desc, t.status, t.result_code, t.result_desc, t.callback_received_at, t.subscriber_id, t.hotspot_purchase_id, t.created_at, t.updated_at, s.pppoe_username, s.full_name, p.name AS plan_name
FROM mpesa_transactions t
LEFT JOIN subscribers s ON s.id = t.subscriber_id
LEFT JOIN hotspot_purchases h ON h.id = t.hotspot_purchase_id
LEFT JOIN plans p ON p.id = COALESCE(h.plan_id, s.plan_id)
WHERE t.purpose = 'customer' AND t.status IN ('success', 'unmatched')
  AND ($2::text IS NULL OR t.status = $2::text)
ORDER BY COALESCE(t.callback_received_at, t.created_at) DESC
LIMIT $1
`

type ListPaymentsParams struct {
	Limit  int32   `json:"limit"`
	Status *string `json:"status"`
}

type ListPaymentsRow struct {
	ID                 uuid.UUID  `json:"id"`
	TenantID           uuid.UUID  `json:"tenant_id"`
	Source             string     `json:"source"`
	Purpose            string     `json:"purpose"`
	MerchantRequestID  *string    `json:"merchant_request_id"`
	CheckoutRequestID  *string    `json:"checkout_request_id"`
	MpesaReceiptNumber *string    `json:"mpesa_receipt_number"`
	PhoneNumber        *string    `json:"phone_number"`
	AmountCents        int32      `json:"amount_cents"`
	AccountReference   string     `json:"account_reference"`
	TransactionDesc    *string    `json:"transaction_desc"`
	Status             string     `json:"status"`
	ResultCode         *int32     `json:"result_code"`
	ResultDesc         *string    `json:"result_desc"`
	CallbackReceivedAt *time.Time `json:"callback_received_at"`
	SubscriberID       *uuid.UUID `json:"subscriber_id"`
	HotspotPurchaseID  *uuid.UUID `json:"hotspot_purchase_id"`
	CreatedAt          time.Time  `json:"created_at"`
	UpdatedAt          time.Time  `json:"updated_at"`
	PppoeUsername      *string    `json:"pppoe_username"`
	FullName           *string    `json:"full_name"`
	PlanName           *string    `json:"plan_name"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]ListPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listPayments, arg.Limit, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsRow{}
	for rows.Next() {
		var i ListPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Source,
			&i.Purpose,
			&i.MerchantRequestID,
			&i.CheckoutRequestID,
			&i.MpesaReceiptNumber,
			&i.PhoneNumber,
			&i.AmountCents,
			&i.AccountReference,
			&i.TransactionDesc,
			&i.Status,
			&i.ResultCode,
			&i.ResultDesc,
			&i.CallbackReceivedAt,
			&i.SubscriberID,
			&i.HotspotPurchaseID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PppoeUsername,
			&i.FullName,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTx = `-- name: ListPendingTx :many
SELECT id, tenant_id, source, purpose, merchant_request_id, checkout_request_id, mpesa_receipt_number, phone_number, amount_cents, account_reference, transaction_desc, status, result_code, result_desc, callback_received_at, subscriber_id, hotspot_purchase_id, created_at, updated_at FROM mpesa_transactions WHERE status = 'pending' AND source = 'stk' AND created_at < $1::timestamptz
ORDER BY created_at LIMIT 100
`

func (q *Queries) ListPendingTx(ctx context.Context, olderThan time.Time) ([]MpesaTransaction, error) {
	rows, err := q.db.Query(ctx, listPendingTx, olderThan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MpesaTransaction{}
	for rows.Next() {
		var i MpesaTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Source,
			&i.Purpose,
			&i.MerchantRequestID,
			&i.CheckoutRequestID,
			&i.MpesaReceiptNumber,
			&i.PhoneNumber,
			&i.AmountCents,
			&i.AccountReference,
			&i.TransactionDesc,
			&i.Status,
			&i.ResultCode,
			&i.ResultDesc,
			&i.CallbackReceivedAt,
			&i.SubscriberID,
			&i.HotspotPurchaseID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchTx = `-- name: MatchTx :exec
UPDATE mpesa_transactions SET status = 'success', subscriber_id = $2, updated_at = NOW() WHERE id = $1 AND status = 'unmatched'
`

type MatchTxParams struct {
	ID           uuid.UUID  `json:"id"`
	SubscriberID *uuid.UUID `json:"subscriber_id"`
}

func (q *Queries) MatchTx(ctx context.Context, arg MatchTxParams) error {
	_, err := q.db.Exec(ctx, matchTx, arg.ID, arg.SubscriberID)
	return err
}

const revenueBetween = `-- name: RevenueBetween :one
SELECT COALESCE(sum(amount_cents), 0)::bigint AS cents
FROM mpesa_transactions WHERE purpose = 'customer' AND status = 'success'
  AND callback_received_at >= $1::timestamptz AND callback_received_at < $2::timestamptz
`

type RevenueBetweenParams struct {
	Since time.Time `json:"since"`
	Until time.Time `json:"until"`
}

func (q *Queries) RevenueBetween(ctx context.Context, arg RevenueBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, revenueBetween, arg.Since, arg.Until)
	var cents int64
	err := row.Scan(&cents)
	return cents, err
}

const revenueBuckets = `-- name: RevenueBuckets :many
SELECT date_bin($1::interval, callback_received_at, $2::timestamptz)::timestamptz AS bucket,
       COALESCE(sum(amount_cents), 0)::bigint AS cents
FROM mpesa_transactions WHERE purpose = 'customer' AND status = 'success'
  AND callback_received_at >= $2::timestamptz AND callback_received_at < $3::timestamptz
GROUP BY 1 ORDER BY 1
`

type RevenueBucketsParams struct {
	Bucket pgtype.Interval `json:"bucket"`
	Since  time.Time       `json:"since"`
	Until  time.Time       `json:"until"`
}

type RevenueBucketsRow struct {
	Bucket time.Time `json:"bucket"`
	Cents  int64     `json:"cents"`
}

func (q *Queries) RevenueBuckets(ctx context.Context, arg RevenueBucketsParams) ([]RevenueBucketsRow, error) {
	rows, err := q.db.Query(ctx, revenueBuckets, arg.Bucket, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueBucketsRow{}
	for rows.Next() {
		var i RevenueBucketsRow
		if err := rows.Scan(&i.Bucket, &i.Cents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueSplit = `-- name: RevenueSplit :many
SELECT CASE WHEN t.hotspot_purchase_id IS NOT NULL THEN 'hotspot' ELSE 'pppoe' END AS kind,
       COALESCE(sum(t.amount_cents), 0)::bigint AS cents
FROM mpesa_transactions t
WHERE t.purpose = 'customer' AND t.status = 'success'
  AND t.callback_received_at >= $1::timestamptz AND t.callback_received_at < $2::timestamptz
GROUP BY 1
`

type RevenueSplitParams struct {
	Since time.Time `json:"since"`
	Until time.Time `json:"until"`
}

type RevenueSplitRow struct {
	Kind  string `json:"kind"`
	Cents int64  `json:"cents"`
}

func (q *Queries) RevenueSplit(ctx context.Context, arg RevenueSplitParams) ([]RevenueSplitRow, error) {
	rows, err := q.db.Query(ctx, revenueSplit, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueSplitRow{}
	for rows.Next() {
		var i RevenueSplitRow
		if err := rows.Scan(&i.Kind, &i.Cents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPlans = `-- name: TopPlans :many
SELECT p.id, p.name, p.access_type, count(t.id)::int AS sold, COALESCE(sum(t.amount_cents), 0)::bigint AS cents
FROM mpesa_transactions t
LEFT JOIN hotspot_purchases h ON h.id = t.hotspot_purchase_id
LEFT JOIN subscribers s ON s.id = t.subscriber_id
JOIN plans p ON p.id = COALESCE(h.plan_id, s.plan_id)
WHERE t.purpose = 'customer' AND t.status = 'success'
  AND t.callback_received_at >= $1::timestamptz AND t.callback_received_at < $2::timestamptz
GROUP BY p.id, p.name, p.access_type
ORDER BY cents DESC LIMIT $3::int
`

type TopPlansParams struct {
	Since time.Time `json:"since"`
	Until time.Time `json:"until"`
	Lim   int32     `json:"lim"`
}

type TopPlansRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	AccessType string    `json:"access_type"`
	Sold       int32     `json:"sold"`
	Cents      int64     `json:"cents"`
}

func (q *Queries) TopPlans(ctx context.Context, arg TopPlansParams) ([]TopPlansRow, error) {
	rows, err := q.db.Query(ctx, topPlans, arg.Since, arg.Until, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopPlansRow{}
	for rows.Next() {
		var i TopPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccessType,
			&i.Sold,
			&i.Cents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const txReceiptExists = `-- name: TxReceiptExists :one
SELECT EXISTS (SELECT 1 FROM mpesa_transactions WHERE mpesa_receipt_number = $1) AS exists
`

func (q *Queries) TxReceiptExists(ctx context.Context, mpesaReceiptNumber *string) (bool, error) {
	row := q.db.QueryRow(ctx, txReceiptExists, mpesaReceiptNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const voucherValueBetween = `-- name: VoucherValueBetween :one
SELECT COALESCE(sum(p.price_cents), 0)::bigint AS cents
FROM vouchers v JOIN plans p ON p.id = v.plan_id
WHERE v.redeemed_at >= $1::timestamptz AND v.redeemed_at < $2::timestamptz
`

type VoucherValueBetweenParams struct {
	Since time.Time `json:"since"`
	Until time.Time `json:"until"`
}

func (q *Queries) VoucherValueBetween(ctx context.Context, arg VoucherValueBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, voucherValueBetween, arg.Since, arg.Until)
	var cents int64
	err := row.Scan(&cents)
	return cents, err
}
