// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: network.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const allocateTunnelIP = `-- name: AllocateTunnelIP :one
SELECT allocate_tunnel_ip($1::cidr)::inet AS ip
`

func (q *Queries) AllocateTunnelIP(ctx context.Context, cidr netip.Prefix) (netip.Addr, error) {
	row := q.db.QueryRow(ctx, allocateTunnelIP, cidr)
	var ip netip.Addr
	err := row.Scan(&ip)
	return ip, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (tenant_id, name, address, lat, lng)
VALUES (app_tenant(), $1, $2, $3, $4)
RETURNING id, tenant_id, name, address, lat, lng, created_at
`

type CreateLocationParams struct {
	Name    string   `json:"name"`
	Address *string  `json:"address"`
	Lat     *float64 `json:"lat"`
	Lng     *float64 `json:"lng"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, createLocation,
		arg.Name,
		arg.Address,
		arg.Lat,
		arg.Lng,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
	)
	return i, err
}

const createOnboardingToken = `-- name: CreateOnboardingToken :exec
INSERT INTO onboarding_tokens (token_hash, tenant_id, router_id, expires_at) VALUES ($1, app_tenant(), $2, $3)
`

type CreateOnboardingTokenParams struct {
	TokenHash []byte    `json:"token_hash"`
	RouterID  uuid.UUID `json:"router_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateOnboardingToken(ctx context.Context, arg CreateOnboardingTokenParams) error {
	_, err := q.db.Exec(ctx, createOnboardingToken, arg.TokenHash, arg.RouterID, arg.ExpiresAt)
	return err
}

const createRouter = `-- name: CreateRouter :one
INSERT INTO routers (id, tenant_id, location_id, name, tunnel_ip, api_password_enc, radius_secret_enc)
VALUES ($1, app_tenant(), $2, $3, $4, $5, $6)
RETURNING id, tenant_id, location_id, name, serial_number, board_name, architecture, firmware_version, tunnel_ip, wg_public_key, api_user, api_password_enc, radius_secret_enc, status, missed_polls, last_seen_at, status_changed_at, last_config_push, config_hash, created_at, updated_at
`

type CreateRouterParams struct {
	ID              uuid.UUID  `json:"id"`
	LocationID      uuid.UUID  `json:"location_id"`
	Name            string     `json:"name"`
	TunnelIp        netip.Addr `json:"tunnel_ip"`
	ApiPasswordEnc  []byte     `json:"api_password_enc"`
	RadiusSecretEnc []byte     `json:"radius_secret_enc"`
}

func (q *Queries) CreateRouter(ctx context.Context, arg CreateRouterParams) (Router, error) {
	row := q.db.QueryRow(ctx, createRouter,
		arg.ID,
		arg.LocationID,
		arg.Name,
		arg.TunnelIp,
		arg.ApiPasswordEnc,
		arg.RadiusSecretEnc,
	)
	var i Router
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.Name,
		&i.SerialNumber,
		&i.BoardName,
		&i.Architecture,
		&i.FirmwareVersion,
		&i.TunnelIp,
		&i.WgPublicKey,
		&i.ApiUser,
		&i.ApiPasswordEnc,
		&i.RadiusSecretEnc,
		&i.Status,
		&i.MissedPolls,
		&i.LastSeenAt,
		&i.StatusChangedAt,
		&i.LastConfigPush,
		&i.ConfigHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRouter = `-- name: DeleteRouter :exec
DELETE FROM routers WHERE id = $1
`

func (q *Queries) DeleteRouter(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRouter, id)
	return err
}

const getLocation = `-- name: GetLocation :one
SELECT id, tenant_id, name, address, lat, lng, created_at FROM locations WHERE id = $1
`

func (q *Queries) GetLocation(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.Lat,
		&i.Lng,
		&i.CreatedAt,
	)
	return i, err
}

const getRouter = `-- name: GetRouter :one
SELECT id, tenant_id, location_id, name, serial_number, board_name, architecture, firmware_version, tunnel_ip, wg_public_key, api_user, api_password_enc, radius_secret_enc, status, missed_polls, last_seen_at, status_changed_at, last_config_push, config_hash, created_at, updated_at FROM routers WHERE id = $1
`

func (q *Queries) GetRouter(ctx context.Context, id uuid.UUID) (Router, error) {
	row := q.db.QueryRow(ctx, getRouter, id)
	var i Router
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.Name,
		&i.SerialNumber,
		&i.BoardName,
		&i.Architecture,
		&i.FirmwareVersion,
		&i.TunnelIp,
		&i.WgPublicKey,
		&i.ApiUser,
		&i.ApiPasswordEnc,
		&i.RadiusSecretEnc,
		&i.Status,
		&i.MissedPolls,
		&i.LastSeenAt,
		&i.StatusChangedAt,
		&i.LastConfigPush,
		&i.ConfigHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConfigAudit = `-- name: InsertConfigAudit :exec
INSERT INTO config_audit (tenant_id, router_id, action, payload, status, error_message, initiated_by)
VALUES (app_tenant(), $1, $2, $3, $4, $5, $6)
`

type InsertConfigAuditParams struct {
	RouterID     *uuid.UUID `json:"router_id"`
	Action       string     `json:"action"`
	Payload      []byte     `json:"payload"`
	Status       string     `json:"status"`
	ErrorMessage *string    `json:"error_message"`
	InitiatedBy  string     `json:"initiated_by"`
}

func (q *Queries) InsertConfigAudit(ctx context.Context, arg InsertConfigAuditParams) error {
	_, err := q.db.Exec(ctx, insertConfigAudit,
		arg.RouterID,
		arg.Action,
		arg.Payload,
		arg.Status,
		arg.ErrorMessage,
		arg.InitiatedBy,
	)
	return err
}

const listConfigAudit = `-- name: ListConfigAudit :many
SELECT id, tenant_id, router_id, action, payload, status, error_message, initiated_by, created_at FROM config_audit WHERE router_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListConfigAuditParams struct {
	RouterID *uuid.UUID `json:"router_id"`
	Limit    int32      `json:"limit"`
}

func (q *Queries) ListConfigAudit(ctx context.Context, arg ListConfigAuditParams) ([]ConfigAudit, error) {
	rows, err := q.db.Query(ctx, listConfigAudit, arg.RouterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigAudit{}
	for rows.Next() {
		var i ConfigAudit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RouterID,
			&i.Action,
			&i.Payload,
			&i.Status,
			&i.ErrorMessage,
			&i.InitiatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, tenant_id, name, address, lat, lng, created_at FROM locations ORDER BY created_at
`

func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.Lat,
			&i.Lng,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouters = `-- name: ListRouters :many
SELECT r.id, r.tenant_id, r.location_id, r.name, r.serial_number, r.board_name, r.architecture, r.firmware_version, r.tunnel_ip, r.wg_public_key, r.api_user, r.api_password_enc, r.radius_secret_enc, r.status, r.missed_polls, r.last_seen_at, r.status_changed_at, r.last_config_push, r.config_hash, r.created_at, r.updated_at, l.name AS location_name,
       (SELECT count(*) FROM sessions s WHERE s.router_id = r.id AND s.status = 'active')::int AS active_sessions
FROM routers r JOIN locations l ON l.id = r.location_id
ORDER BY CASE r.status WHEN 'offline' THEN 0 WHEN 'degraded' THEN 1 WHEN 'misconfigured' THEN 2 WHEN 'pending' THEN 3 ELSE 4 END, r.name
`

type ListRoutersRow struct {
	ID              uuid.UUID  `json:"id"`
	TenantID        uuid.UUID  `json:"tenant_id"`
	LocationID      uuid.UUID  `json:"location_id"`
	Name            string     `json:"name"`
	SerialNumber    *string    `json:"serial_number"`
	BoardName       *string    `json:"board_name"`
	Architecture    *string    `json:"architecture"`
	FirmwareVersion *string    `json:"firmware_version"`
	TunnelIp        netip.Addr `json:"tunnel_ip"`
	WgPublicKey     *string    `json:"wg_public_key"`
	ApiUser         string     `json:"api_user"`
	ApiPasswordEnc  []byte     `json:"api_password_enc"`
	RadiusSecretEnc []byte     `json:"radius_secret_enc"`
	Status          string     `json:"status"`
	MissedPolls     int32      `json:"missed_polls"`
	LastSeenAt      *time.Time `json:"last_seen_at"`
	StatusChangedAt time.Time  `json:"status_changed_at"`
	LastConfigPush  *time.Time `json:"last_config_push"`
	ConfigHash      *string    `json:"config_hash"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	LocationName    string     `json:"location_name"`
	ActiveSessions  int32      `json:"active_sessions"`
}

func (q *Queries) ListRouters(ctx context.Context) ([]ListRoutersRow, error) {
	rows, err := q.db.Query(ctx, listRouters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoutersRow{}
	for rows.Next() {
		var i ListRoutersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LocationID,
			&i.Name,
			&i.SerialNumber,
			&i.BoardName,
			&i.Architecture,
			&i.FirmwareVersion,
			&i.TunnelIp,
			&i.WgPublicKey,
			&i.ApiUser,
			&i.ApiPasswordEnc,
			&i.RadiusSecretEnc,
			&i.Status,
			&i.MissedPolls,
			&i.LastSeenAt,
			&i.StatusChangedAt,
			&i.LastConfigPush,
			&i.ConfigHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationName,
			&i.ActiveSessions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupOnboardingToken = `-- name: LookupOnboardingToken :one
SELECT t.tenant_id::uuid AS tenant_id, t.router_id::uuid AS router_id, t.expires_at::timestamptz AS expires_at, (t.used_at IS NOT NULL)::bool AS used FROM onboarding_token_lookup($1::bytea) t
`

type LookupOnboardingTokenRow struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	RouterID  uuid.UUID `json:"router_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
}

func (q *Queries) LookupOnboardingToken(ctx context.Context, tokenHash []byte) (LookupOnboardingTokenRow, error) {
	row := q.db.QueryRow(ctx, lookupOnboardingToken, tokenHash)
	var i LookupOnboardingTokenRow
	err := row.Scan(
		&i.TenantID,
		&i.RouterID,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const markConfigPushed = `-- name: MarkConfigPushed :exec
UPDATE routers SET last_config_push = NOW(), config_hash = $2, updated_at = NOW() WHERE id = $1
`

type MarkConfigPushedParams struct {
	ID         uuid.UUID `json:"id"`
	ConfigHash *string   `json:"config_hash"`
}

func (q *Queries) MarkConfigPushed(ctx context.Context, arg MarkConfigPushedParams) error {
	_, err := q.db.Exec(ctx, markConfigPushed, arg.ID, arg.ConfigHash)
	return err
}

const recordPollFailure = `-- name: RecordPollFailure :one
UPDATE routers SET
    missed_polls = missed_polls + 1,
    status = CASE
        WHEN status = 'pending' THEN 'pending'
        WHEN missed_polls + 1 >= $1::int THEN 'offline'
        WHEN missed_polls + 1 >= $2::int THEN 'degraded'
        ELSE status END,
    status_changed_at = CASE
        WHEN status <> 'pending' AND status <> 'offline' AND missed_polls + 1 >= $1::int THEN NOW()
        WHEN status = 'online' AND missed_polls + 1 >= $2::int THEN NOW()
        ELSE status_changed_at END,
    updated_at = NOW()
WHERE id = $3
RETURNING id, tenant_id, location_id, name, serial_number, board_name, architecture, firmware_version, tunnel_ip, wg_public_key, api_user, api_password_enc, radius_secret_enc, status, missed_polls, last_seen_at, status_changed_at, last_config_push, config_hash, created_at, updated_at
`

type RecordPollFailureParams struct {
	OfflineAfter  int32     `json:"offline_after"`
	DegradedAfter int32     `json:"degraded_after"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) RecordPollFailure(ctx context.Context, arg RecordPollFailureParams) (Router, error) {
	row := q.db.QueryRow(ctx, recordPollFailure, arg.OfflineAfter, arg.DegradedAfter, arg.ID)
	var i Router
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.Name,
		&i.SerialNumber,
		&i.BoardName,
		&i.Architecture,
		&i.FirmwareVersion,
		&i.TunnelIp,
		&i.WgPublicKey,
		&i.ApiUser,
		&i.ApiPasswordEnc,
		&i.RadiusSecretEnc,
		&i.Status,
		&i.MissedPolls,
		&i.LastSeenAt,
		&i.StatusChangedAt,
		&i.LastConfigPush,
		&i.ConfigHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordPollSuccess = `-- name: RecordPollSuccess :one
UPDATE routers SET
    missed_polls = 0,
    last_seen_at = NOW(),
    status_changed_at = CASE WHEN status <> 'online' THEN NOW() ELSE status_changed_at END,
    status = 'online',
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, location_id, name, serial_number, board_name, architecture, firmware_version, tunnel_ip, wg_public_key, api_user, api_password_enc, radius_secret_enc, status, missed_polls, last_seen_at, status_changed_at, last_config_push, config_hash, created_at, updated_at
`

func (q *Queries) RecordPollSuccess(ctx context.Context, id uuid.UUID) (Router, error) {
	row := q.db.QueryRow(ctx, recordPollSuccess, id)
	var i Router
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.Name,
		&i.SerialNumber,
		&i.BoardName,
		&i.Architecture,
		&i.FirmwareVersion,
		&i.TunnelIp,
		&i.WgPublicKey,
		&i.ApiUser,
		&i.ApiPasswordEnc,
		&i.RadiusSecretEnc,
		&i.Status,
		&i.MissedPolls,
		&i.LastSeenAt,
		&i.StatusChangedAt,
		&i.LastConfigPush,
		&i.ConfigHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordRouterIdentity = `-- name: RecordRouterIdentity :exec
UPDATE routers SET serial_number = $2, board_name = $3, architecture = $4, firmware_version = $5, updated_at = NOW()
WHERE id = $1
`

type RecordRouterIdentityParams struct {
	ID              uuid.UUID `json:"id"`
	SerialNumber    *string   `json:"serial_number"`
	BoardName       *string   `json:"board_name"`
	Architecture    *string   `json:"architecture"`
	FirmwareVersion *string   `json:"firmware_version"`
}

func (q *Queries) RecordRouterIdentity(ctx context.Context, arg RecordRouterIdentityParams) error {
	_, err := q.db.Exec(ctx, recordRouterIdentity,
		arg.ID,
		arg.SerialNumber,
		arg.BoardName,
		arg.Architecture,
		arg.FirmwareVersion,
	)
	return err
}

const routerByTunnelIP = `-- name: RouterByTunnelIP :one
SELECT t.router_id::uuid AS router_id, t.tenant_id::uuid AS tenant_id FROM router_by_tunnel_ip($1::inet) t
`

type RouterByTunnelIPRow struct {
	RouterID uuid.UUID `json:"router_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) RouterByTunnelIP(ctx context.Context, ip netip.Addr) (RouterByTunnelIPRow, error) {
	row := q.db.QueryRow(ctx, routerByTunnelIP, ip)
	var i RouterByTunnelIPRow
	err := row.Scan(&i.RouterID, &i.TenantID)
	return i, err
}

const routerTargets = `-- name: RouterTargets :many
SELECT t.router_id::uuid AS router_id, t.tenant_id::uuid AS tenant_id FROM router_targets() t
`

type RouterTargetsRow struct {
	RouterID uuid.UUID `json:"router_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) RouterTargets(ctx context.Context) ([]RouterTargetsRow, error) {
	rows, err := q.db.Query(ctx, routerTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RouterTargetsRow{}
	for rows.Next() {
		var i RouterTargetsRow
		if err := rows.Scan(&i.RouterID, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRouterPublicKey = `-- name: SetRouterPublicKey :exec
UPDATE routers SET wg_public_key = $2, updated_at = NOW() WHERE id = $1
`

type SetRouterPublicKeyParams struct {
	ID          uuid.UUID `json:"id"`
	WgPublicKey *string   `json:"wg_public_key"`
}

func (q *Queries) SetRouterPublicKey(ctx context.Context, arg SetRouterPublicKeyParams) error {
	_, err := q.db.Exec(ctx, setRouterPublicKey, arg.ID, arg.WgPublicKey)
	return err
}

const setRouterStatus = `-- name: SetRouterStatus :exec
UPDATE routers SET status = $2, status_changed_at = NOW(), updated_at = NOW() WHERE id = $1
`

type SetRouterStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetRouterStatus(ctx context.Context, arg SetRouterStatusParams) error {
	_, err := q.db.Exec(ctx, setRouterStatus, arg.ID, arg.Status)
	return err
}

const useOnboardingToken = `-- name: UseOnboardingToken :execrows
UPDATE onboarding_tokens SET used_at = NOW() WHERE token_hash = $1 AND used_at IS NULL AND expires_at > NOW()
`

func (q *Queries) UseOnboardingToken(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, useOnboardingToken, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const wireguardPeers = `-- name: WireguardPeers :many
SELECT t.router_id::uuid AS router_id, t.public_key::text AS public_key, t.tunnel_ip::inet AS tunnel_ip FROM wireguard_peers() t
`

type WireguardPeersRow struct {
	RouterID  uuid.UUID  `json:"router_id"`
	PublicKey string     `json:"public_key"`
	TunnelIp  netip.Addr `json:"tunnel_ip"`
}

func (q *Queries) WireguardPeers(ctx context.Context) ([]WireguardPeersRow, error) {
	rows, err := q.db.Query(ctx, wireguardPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WireguardPeersRow{}
	for rows.Next() {
		var i WireguardPeersRow
		if err := rows.Scan(&i.RouterID, &i.PublicKey, &i.TunnelIp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
