// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: plans.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (tenant_id, location_id, name, access_type, price_cents, duration_days, duration_minutes, is_trial,
                   data_cap_mb, bandwidth_down_kbps, bandwidth_up_kbps, max_devices, mikrotik_profile_name, sort_order)
VALUES (app_tenant(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, tenant_id, location_id, name, access_type, price_cents, currency, duration_days, duration_minutes, is_trial, data_cap_mb, bandwidth_down_kbps, bandwidth_up_kbps, max_devices, mikrotik_profile_name, is_active, sort_order, created_at
`

type CreatePlanParams struct {
	LocationID          *uuid.UUID `json:"location_id"`
	Name                string     `json:"name"`
	AccessType          string     `json:"access_type"`
	PriceCents          int32      `json:"price_cents"`
	DurationDays        *int32     `json:"duration_days"`
	DurationMinutes     *int32     `json:"duration_minutes"`
	IsTrial             bool       `json:"is_trial"`
	DataCapMb           *int64     `json:"data_cap_mb"`
	BandwidthDownKbps   int32      `json:"bandwidth_down_kbps"`
	BandwidthUpKbps     int32      `json:"bandwidth_up_kbps"`
	MaxDevices          int32      `json:"max_devices"`
	MikrotikProfileName *string    `json:"mikrotik_profile_name"`
	SortOrder           int32      `json:"sort_order"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.LocationID,
		arg.Name,
		arg.AccessType,
		arg.PriceCents,
		arg.DurationDays,
		arg.DurationMinutes,
		arg.IsTrial,
		arg.DataCapMb,
		arg.BandwidthDownKbps,
		arg.BandwidthUpKbps,
		arg.MaxDevices,
		arg.MikrotikProfileName,
		arg.SortOrder,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.Name,
		&i.AccessType,
		&i.PriceCents,
		&i.Currency,
		&i.DurationDays,
		&i.DurationMinutes,
		&i.IsTrial,
		&i.DataCapMb,
		&i.BandwidthDownKbps,
		&i.BandwidthUpKbps,
		&i.MaxDevices,
		&i.MikrotikProfileName,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, tenant_id, location_id, name, access_type, price_cents, currency, duration_days, duration_minutes, is_trial, data_cap_mb, bandwidth_down_kbps, bandwidth_up_kbps, max_devices, mikrotik_profile_name, is_active, sort_order, created_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.Name,
		&i.AccessType,
		&i.PriceCents,
		&i.Currency,
		&i.DurationDays,
		&i.DurationMinutes,
		&i.IsTrial,
		&i.DataCapMb,
		&i.BandwidthDownKbps,
		&i.BandwidthUpKbps,
		&i.MaxDevices,
		&i.MikrotikProfileName,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveHotspotPlans = `-- name: ListActiveHotspotPlans :many
SELECT id, tenant_id, location_id, name, access_type, price_cents, currency, duration_days, duration_minutes, is_trial, data_cap_mb, bandwidth_down_kbps, bandwidth_up_kbps, max_devices, mikrotik_profile_name, is_active, sort_order, created_at FROM plans WHERE access_type = 'hotspot' AND is_active ORDER BY is_trial DESC, sort_order, price_cents
`

func (q *Queries) ListActiveHotspotPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listActiveHotspotPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LocationID,
			&i.Name,
			&i.AccessType,
			&i.PriceCents,
			&i.Currency,
			&i.DurationDays,
			&i.DurationMinutes,
			&i.IsTrial,
			&i.DataCapMb,
			&i.BandwidthDownKbps,
			&i.BandwidthUpKbps,
			&i.MaxDevices,
			&i.MikrotikProfileName,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, tenant_id, location_id, name, access_type, price_cents, currency, duration_days, duration_minutes, is_trial, data_cap_mb, bandwidth_down_kbps, bandwidth_up_kbps, max_devices, mikrotik_profile_name, is_active, sort_order, created_at FROM plans
WHERE ($1::text IS NULL OR access_type = $1::text)
ORDER BY access_type, sort_order, price_cents
`

func (q *Queries) ListPlans(ctx context.Context, accessType *string) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans, accessType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LocationID,
			&i.Name,
			&i.AccessType,
			&i.PriceCents,
			&i.Currency,
			&i.DurationDays,
			&i.DurationMinutes,
			&i.IsTrial,
			&i.DataCapMb,
			&i.BandwidthDownKbps,
			&i.BandwidthUpKbps,
			&i.MaxDevices,
			&i.MikrotikProfileName,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans SET name = $2, price_cents = $3, duration_days = $4, duration_minutes = $5, data_cap_mb = $6,
    bandwidth_down_kbps = $7, bandwidth_up_kbps = $8, max_devices = $9, is_active = $10, sort_order = $11
WHERE id = $1
RETURNING id, tenant_id, location_id, name, access_type, price_cents, currency, duration_days, duration_minutes, is_trial, data_cap_mb, bandwidth_down_kbps, bandwidth_up_kbps, max_devices, mikrotik_profile_name, is_active, sort_order, created_at
`

type UpdatePlanParams struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	PriceCents        int32     `json:"price_cents"`
	DurationDays      *int32    `json:"duration_days"`
	DurationMinutes   *int32    `json:"duration_minutes"`
	DataCapMb         *int64    `json:"data_cap_mb"`
	BandwidthDownKbps int32     `json:"bandwidth_down_kbps"`
	BandwidthUpKbps   int32     `json:"bandwidth_up_kbps"`
	MaxDevices        int32     `json:"max_devices"`
	IsActive          bool      `json:"is_active"`
	SortOrder         int32     `json:"sort_order"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.PriceCents,
		arg.DurationDays,
		arg.DurationMinutes,
		arg.DataCapMb,
		arg.BandwidthDownKbps,
		arg.BandwidthUpKbps,
		arg.MaxDevices,
		arg.IsActive,
		arg.SortOrder,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.Name,
		&i.AccessType,
		&i.PriceCents,
		&i.Currency,
		&i.DurationDays,
		&i.DurationMinutes,
		&i.IsTrial,
		&i.DataCapMb,
		&i.BandwidthDownKbps,
		&i.BandwidthUpKbps,
		&i.MaxDevices,
		&i.MikrotikProfileName,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
