// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const activeSessionsForUsername = `-- name: ActiveSessionsForUsername :many
SELECT s.id, s.tenant_id, s.router_id, s.plan_id, s.access_type, s.username, s.acct_session_id, s.mac_address, s.ip_address, s.status, s.started_at, s.terminated_at, s.termination_cause, s.bytes_in, s.bytes_out, s.session_time_sec, s.updated_at, r.tunnel_ip FROM sessions s JOIN routers r ON r.id = s.router_id
WHERE s.username = $1 AND s.status = 'active'
`

type ActiveSessionsForUsernameRow struct {
	ID               uuid.UUID   `json:"id"`
	TenantID         uuid.UUID   `json:"tenant_id"`
	RouterID         uuid.UUID   `json:"router_id"`
	PlanID           *uuid.UUID  `json:"plan_id"`
	AccessType       string      `json:"access_type"`
	Username         string      `json:"username"`
	AcctSessionID    string      `json:"acct_session_id"`
	MacAddress       *string     `json:"mac_address"`
	IpAddress        *netip.Addr `json:"ip_address"`
	Status           string      `json:"status"`
	StartedAt        time.Time   `json:"started_at"`
	TerminatedAt     *time.Time  `json:"terminated_at"`
	TerminationCause *string     `json:"termination_cause"`
	BytesIn          int64       `json:"bytes_in"`
	BytesOut         int64       `json:"bytes_out"`
	SessionTimeSec   int32       `json:"session_time_sec"`
	UpdatedAt        time.Time   `json:"updated_at"`
	TunnelIp         netip.Addr  `json:"tunnel_ip"`
}

func (q *Queries) ActiveSessionsForUsername(ctx context.Context, username string) ([]ActiveSessionsForUsernameRow, error) {
	rows, err := q.db.Query(ctx, activeSessionsForUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveSessionsForUsernameRow{}
	for rows.Next() {
		var i ActiveSessionsForUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RouterID,
			&i.PlanID,
			&i.AccessType,
			&i.Username,
			&i.AcctSessionID,
			&i.MacAddress,
			&i.IpAddress,
			&i.Status,
			&i.StartedAt,
			&i.TerminatedAt,
			&i.TerminationCause,
			&i.BytesIn,
			&i.BytesOut,
			&i.SessionTimeSec,
			&i.UpdatedAt,
			&i.TunnelIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bytesUsedSince = `-- name: BytesUsedSince :one
SELECT COALESCE(sum(bytes_in + bytes_out), 0)::bigint FROM sessions WHERE username = $1 AND started_at >= $2::timestamptz
`

type BytesUsedSinceParams struct {
	Username string    `json:"username"`
	Since    time.Time `json:"since"`
}

func (q *Queries) BytesUsedSince(ctx context.Context, arg BytesUsedSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, bytesUsedSince, arg.Username, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const closeStaleSessions = `-- name: CloseStaleSessions :exec
UPDATE sessions SET status = 'terminated', terminated_at = NOW(), termination_cause = 'Stale'
WHERE status = 'active' AND updated_at < $1::timestamptz
`

func (q *Queries) CloseStaleSessions(ctx context.Context, before time.Time) error {
	_, err := q.db.Exec(ctx, closeStaleSessions, before)
	return err
}

const countActiveSessions = `-- name: CountActiveSessions :many
SELECT access_type, count(*)::int AS n FROM sessions WHERE status = 'active' GROUP BY access_type
`

type CountActiveSessionsRow struct {
	AccessType string `json:"access_type"`
	N          int32  `json:"n"`
}

func (q *Queries) CountActiveSessions(ctx context.Context) ([]CountActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, countActiveSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountActiveSessionsRow{}
	for rows.Next() {
		var i CountActiveSessionsRow
		if err := rows.Scan(&i.AccessType, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countActiveSessionsBetween = `-- name: CountActiveSessionsBetween :one
SELECT count(DISTINCT username)::int FROM sessions WHERE started_at < $1::timestamptz AND (terminated_at IS NULL OR terminated_at > $1::timestamptz)
`

func (q *Queries) CountActiveSessionsBetween(ctx context.Context, at time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsBetween, at)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const startSession = `-- name: StartSession :one
INSERT INTO sessions (tenant_id, router_id, plan_id, access_type, username, acct_session_id, mac_address, ip_address)
VALUES (app_tenant(), $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (router_id, acct_session_id) DO UPDATE SET status = 'active', updated_at = NOW()
RETURNING id, tenant_id, router_id, plan_id, access_type, username, acct_session_id, mac_address, ip_address, status, started_at, terminated_at, termination_cause, bytes_in, bytes_out, session_time_sec, updated_at
`

type StartSessionParams struct {
	RouterID      uuid.UUID   `json:"router_id"`
	PlanID        *uuid.UUID  `json:"plan_id"`
	AccessType    string      `json:"access_type"`
	Username      string      `json:"username"`
	AcctSessionID string      `json:"acct_session_id"`
	MacAddress    *string     `json:"mac_address"`
	IpAddress     *netip.Addr `json:"ip_address"`
}

func (q *Queries) StartSession(ctx context.Context, arg StartSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, startSession,
		arg.RouterID,
		arg.PlanID,
		arg.AccessType,
		arg.Username,
		arg.AcctSessionID,
		arg.MacAddress,
		arg.IpAddress,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.PlanID,
		&i.AccessType,
		&i.Username,
		&i.AcctSessionID,
		&i.MacAddress,
		&i.IpAddress,
		&i.Status,
		&i.StartedAt,
		&i.TerminatedAt,
		&i.TerminationCause,
		&i.BytesIn,
		&i.BytesOut,
		&i.SessionTimeSec,
		&i.UpdatedAt,
	)
	return i, err
}

const stopSession = `-- name: StopSession :exec
UPDATE sessions SET status = 'terminated', terminated_at = NOW(), termination_cause = $3,
    bytes_in = $4, bytes_out = $5, session_time_sec = $6, updated_at = NOW()
WHERE router_id = $1 AND acct_session_id = $2
`

type StopSessionParams struct {
	RouterID         uuid.UUID `json:"router_id"`
	AcctSessionID    string    `json:"acct_session_id"`
	TerminationCause *string   `json:"termination_cause"`
	BytesIn          int64     `json:"bytes_in"`
	BytesOut         int64     `json:"bytes_out"`
	SessionTimeSec   int32     `json:"session_time_sec"`
}

func (q *Queries) StopSession(ctx context.Context, arg StopSessionParams) error {
	_, err := q.db.Exec(ctx, stopSession,
		arg.RouterID,
		arg.AcctSessionID,
		arg.TerminationCause,
		arg.BytesIn,
		arg.BytesOut,
		arg.SessionTimeSec,
	)
	return err
}

const updateSessionCounters = `-- name: UpdateSessionCounters :one
UPDATE sessions SET bytes_in = $3, bytes_out = $4, session_time_sec = $5, ip_address = COALESCE($6::inet, ip_address), updated_at = NOW()
WHERE router_id = $1 AND acct_session_id = $2
RETURNING id, tenant_id, router_id, plan_id, access_type, username, acct_session_id, mac_address, ip_address, status, started_at, terminated_at, termination_cause, bytes_in, bytes_out, session_time_sec, updated_at
`

type UpdateSessionCountersParams struct {
	RouterID       uuid.UUID   `json:"router_id"`
	AcctSessionID  string      `json:"acct_session_id"`
	BytesIn        int64       `json:"bytes_in"`
	BytesOut       int64       `json:"bytes_out"`
	SessionTimeSec int32       `json:"session_time_sec"`
	Ip             *netip.Addr `json:"ip"`
}

func (q *Queries) UpdateSessionCounters(ctx context.Context, arg UpdateSessionCountersParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionCounters,
		arg.RouterID,
		arg.AcctSessionID,
		arg.BytesIn,
		arg.BytesOut,
		arg.SessionTimeSec,
		arg.Ip,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RouterID,
		&i.PlanID,
		&i.AccessType,
		&i.Username,
		&i.AcctSessionID,
		&i.MacAddress,
		&i.IpAddress,
		&i.Status,
		&i.StartedAt,
		&i.TerminatedAt,
		&i.TerminationCause,
		&i.BytesIn,
		&i.BytesOut,
		&i.SessionTimeSec,
		&i.UpdatedAt,
	)
	return i, err
}
