// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sms.sql

package store

import (
	"context"
)

const insertSMS = `-- name: InsertSMS :exec
INSERT INTO sms_messages (tenant_id, to_number, body, kind, status, credits, provider_id, error_message)
VALUES (app_tenant(), $1, $2, $3, $4, $5, $6, $7)
`

type InsertSMSParams struct {
	ToNumber     string  `json:"to_number"`
	Body         string  `json:"body"`
	Kind         string  `json:"kind"`
	Status       string  `json:"status"`
	Credits      int32   `json:"credits"`
	ProviderID   *string `json:"provider_id"`
	ErrorMessage *string `json:"error_message"`
}

func (q *Queries) InsertSMS(ctx context.Context, arg InsertSMSParams) error {
	_, err := q.db.Exec(ctx, insertSMS,
		arg.ToNumber,
		arg.Body,
		arg.Kind,
		arg.Status,
		arg.Credits,
		arg.ProviderID,
		arg.ErrorMessage,
	)
	return err
}

const listSMS = `-- name: ListSMS :many
SELECT id, tenant_id, to_number, body, kind, status, credits, provider_id, error_message, created_at FROM sms_messages ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListSMS(ctx context.Context, limit int32) ([]SmsMessage, error) {
	rows, err := q.db.Query(ctx, listSMS, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsMessage{}
	for rows.Next() {
		var i SmsMessage
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ToNumber,
			&i.Body,
			&i.Kind,
			&i.Status,
			&i.Credits,
			&i.ProviderID,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
