// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: subscribers.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applySubscriberPayment = `-- name: ApplySubscriberPayment :one
UPDATE subscribers SET next_renewal_at = $2, credit_cents = $3, status = $4, reminder_stage = 0, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, location_id, full_name, phone_number, email, physical_address, pppoe_username, pppoe_password_enc, status, plan_id, next_renewal_at, credit_cents, auto_renew, reminder_stage, created_at, updated_at
`

type ApplySubscriberPaymentParams struct {
	ID            uuid.UUID  `json:"id"`
	NextRenewalAt *time.Time `json:"next_renewal_at"`
	CreditCents   int32      `json:"credit_cents"`
	Status        string     `json:"status"`
}

func (q *Queries) ApplySubscriberPayment(ctx context.Context, arg ApplySubscriberPaymentParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, applySubscriberPayment,
		arg.ID,
		arg.NextRenewalAt,
		arg.CreditCents,
		arg.Status,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.PhysicalAddress,
		&i.PppoeUsername,
		&i.PppoePasswordEnc,
		&i.Status,
		&i.PlanID,
		&i.NextRenewalAt,
		&i.CreditCents,
		&i.AutoRenew,
		&i.ReminderStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countRenewalsDue = `-- name: CountRenewalsDue :one
SELECT count(*)::int FROM subscribers WHERE status = 'active' AND next_renewal_at BETWEEN NOW() AND NOW() + INTERVAL '3 days'
`

func (q *Queries) CountRenewalsDue(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countRenewalsDue)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSubscribersByStatus = `-- name: CountSubscribersByStatus :many
SELECT status, count(*)::int AS n FROM subscribers GROUP BY status
`

type CountSubscribersByStatusRow struct {
	Status string `json:"status"`
	N      int32  `json:"n"`
}

func (q *Queries) CountSubscribersByStatus(ctx context.Context) ([]CountSubscribersByStatusRow, error) {
	rows, err := q.db.Query(ctx, countSubscribersByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountSubscribersByStatusRow{}
	for rows.Next() {
		var i CountSubscribersByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSubscriber = `-- name: CreateSubscriber :one
INSERT INTO subscribers (id, tenant_id, location_id, full_name, phone_number, email, physical_address,
                         pppoe_username, pppoe_password_enc, plan_id, next_renewal_at, status)
VALUES ($1, app_tenant(), $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, location_id, full_name, phone_number, email, physical_address, pppoe_username, pppoe_password_enc, status, plan_id, next_renewal_at, credit_cents, auto_renew, reminder_stage, created_at, updated_at
`

type CreateSubscriberParams struct {
	ID               uuid.UUID  `json:"id"`
	LocationID       *uuid.UUID `json:"location_id"`
	FullName         string     `json:"full_name"`
	PhoneNumber      string     `json:"phone_number"`
	Email            *string    `json:"email"`
	PhysicalAddress  *string    `json:"physical_address"`
	PppoeUsername    string     `json:"pppoe_username"`
	PppoePasswordEnc []byte     `json:"pppoe_password_enc"`
	PlanID           *uuid.UUID `json:"plan_id"`
	NextRenewalAt    *time.Time `json:"next_renewal_at"`
	Status           string     `json:"status"`
}

func (q *Queries) CreateSubscriber(ctx context.Context, arg CreateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, createSubscriber,
		arg.ID,
		arg.LocationID,
		arg.FullName,
		arg.PhoneNumber,
		arg.Email,
		arg.PhysicalAddress,
		arg.PppoeUsername,
		arg.PppoePasswordEnc,
		arg.PlanID,
		arg.NextRenewalAt,
		arg.Status,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.PhysicalAddress,
		&i.PppoeUsername,
		&i.PppoePasswordEnc,
		&i.Status,
		&i.PlanID,
		&i.NextRenewalAt,
		&i.CreditCents,
		&i.AutoRenew,
		&i.ReminderStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriber = `-- name: GetSubscriber :one
SELECT id, tenant_id, location_id, full_name, phone_number, email, physical_address, pppoe_username, pppoe_password_enc, status, plan_id, next_renewal_at, credit_cents, auto_renew, reminder_stage, created_at, updated_at FROM subscribers WHERE id = $1
`

func (q *Queries) GetSubscriber(ctx context.Context, id uuid.UUID) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriber, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.PhysicalAddress,
		&i.PppoeUsername,
		&i.PppoePasswordEnc,
		&i.Status,
		&i.PlanID,
		&i.NextRenewalAt,
		&i.CreditCents,
		&i.AutoRenew,
		&i.ReminderStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberByUsername = `-- name: GetSubscriberByUsername :one
SELECT id, tenant_id, location_id, full_name, phone_number, email, physical_address, pppoe_username, pppoe_password_enc, status, plan_id, next_renewal_at, credit_cents, auto_renew, reminder_stage, created_at, updated_at FROM subscribers WHERE pppoe_username = upper(trim($1::text))
`

func (q *Queries) GetSubscriberByUsername(ctx context.Context, username string) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberByUsername, username)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.PhysicalAddress,
		&i.PppoeUsername,
		&i.PppoePasswordEnc,
		&i.Status,
		&i.PlanID,
		&i.NextRenewalAt,
		&i.CreditCents,
		&i.AutoRenew,
		&i.ReminderStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberForUpdate = `-- name: GetSubscriberForUpdate :one
SELECT id, tenant_id, location_id, full_name, phone_number, email, physical_address, pppoe_username, pppoe_password_enc, status, plan_id, next_renewal_at, credit_cents, auto_renew, reminder_stage, created_at, updated_at FROM subscribers WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSubscriberForUpdate(ctx context.Context, id uuid.UUID) (Subscriber, error) {
	row := q.db.QueryRow(ctx, getSubscriberForUpdate, id)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.PhysicalAddress,
		&i.PppoeUsername,
		&i.PppoePasswordEnc,
		&i.Status,
		&i.PlanID,
		&i.NextRenewalAt,
		&i.CreditCents,
		&i.AutoRenew,
		&i.ReminderStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredActive = `-- name: ListExpiredActive :many
SELECT id, tenant_id, location_id, full_name, phone_number, email, physical_address, pppoe_username, pppoe_password_enc, status, plan_id, next_renewal_at, credit_cents, auto_renew, reminder_stage, created_at, updated_at FROM subscribers WHERE status = 'active' AND next_renewal_at IS NOT NULL AND next_renewal_at <= NOW()
`

func (q *Queries) ListExpiredActive(ctx context.Context) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listExpiredActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscriber{}
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LocationID,
			&i.FullName,
			&i.PhoneNumber,
			&i.Email,
			&i.PhysicalAddress,
			&i.PppoeUsername,
			&i.PppoePasswordEnc,
			&i.Status,
			&i.PlanID,
			&i.NextRenewalAt,
			&i.CreditCents,
			&i.AutoRenew,
			&i.ReminderStage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraceOver = `-- name: ListGraceOver :many
SELECT id, tenant_id, location_id, full_name, phone_number, email, physical_address, pppoe_username, pppoe_password_enc, status, plan_id, next_renewal_at, credit_cents, auto_renew, reminder_stage, created_at, updated_at FROM subscribers WHERE status = 'expired' AND next_renewal_at + make_interval(hours => $1::int) <= NOW()
`

func (q *Queries) ListGraceOver(ctx context.Context, graceHours int32) ([]Subscriber, error) {
	rows, err := q.db.Query(ctx, listGraceOver, graceHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscriber{}
	for rows.Next() {
		var i Subscriber
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LocationID,
			&i.FullName,
			&i.PhoneNumber,
			&i.Email,
			&i.PhysicalAddress,
			&i.PppoeUsername,
			&i.PppoePasswordEnc,
			&i.Status,
			&i.PlanID,
			&i.NextRenewalAt,
			&i.CreditCents,
			&i.AutoRenew,
			&i.ReminderStage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminderCandidates = `-- name: ListReminderCandidates :many
SELECT s.id, s.tenant_id, s.location_id, s.full_name, s.phone_number, s.email, s.physical_address, s.pppoe_username, s.pppoe_password_enc, s.status, s.plan_id, s.next_renewal_at, s.credit_cents, s.auto_renew, s.reminder_stage, s.created_at, s.updated_at, p.price_cents AS plan_price_cents FROM subscribers s LEFT JOIN plans p ON p.id = s.plan_id
WHERE s.status = 'active' AND s.next_renewal_at IS NOT NULL
  AND ((s.reminder_stage < 1 AND s.next_renewal_at <= NOW() + INTERVAL '3 days' AND s.next_renewal_at > NOW() + INTERVAL '1 day')
    OR (s.reminder_stage < 2 AND s.next_renewal_at <= NOW() + INTERVAL '1 day' AND s.next_renewal_at > NOW()))
`

type ListReminderCandidatesRow struct {
	ID               uuid.UUID  `json:"id"`
	TenantID         uuid.UUID  `json:"tenant_id"`
	LocationID       *uuid.UUID `json:"location_id"`
	FullName         string     `json:"full_name"`
	PhoneNumber      string     `json:"phone_number"`
	Email            *string    `json:"email"`
	PhysicalAddress  *string    `json:"physical_address"`
	PppoeUsername    string     `json:"pppoe_username"`
	PppoePasswordEnc []byte     `json:"pppoe_password_enc"`
	Status           string     `json:"status"`
	PlanID           *uuid.UUID `json:"plan_id"`
	NextRenewalAt    *time.Time `json:"next_renewal_at"`
	CreditCents      int32      `json:"credit_cents"`
	AutoRenew        bool       `json:"auto_renew"`
	ReminderStage    int32      `json:"reminder_stage"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	PlanPriceCents   *int32     `json:"plan_price_cents"`
}

func (q *Queries) ListReminderCandidates(ctx context.Context) ([]ListReminderCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listReminderCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReminderCandidatesRow{}
	for rows.Next() {
		var i ListReminderCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LocationID,
			&i.FullName,
			&i.PhoneNumber,
			&i.Email,
			&i.PhysicalAddress,
			&i.PppoeUsername,
			&i.PppoePasswordEnc,
			&i.Status,
			&i.PlanID,
			&i.NextRenewalAt,
			&i.CreditCents,
			&i.AutoRenew,
			&i.ReminderStage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanPriceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscribers = `-- name: ListSubscribers :many
SELECT s.id, s.tenant_id, s.location_id, s.full_name, s.phone_number, s.email, s.physical_address, s.pppoe_username, s.pppoe_password_enc, s.status, s.plan_id, s.next_renewal_at, s.credit_cents, s.auto_renew, s.reminder_stage, s.created_at, s.updated_at, p.name AS plan_name, p.price_cents AS plan_price_cents,
       EXISTS (SELECT 1 FROM sessions x WHERE x.username = s.pppoe_username AND x.status = 'active') AS online
FROM subscribers s LEFT JOIN plans p ON p.id = s.plan_id
WHERE ($3::text IS NULL OR s.status = $3::text)
  AND ($4::text IS NULL
       OR s.full_name ILIKE '%' || $4::text || '%'
       OR s.pppoe_username ILIKE '%' || $4::text || '%'
       OR s.phone_number LIKE '%' || $4::text || '%')
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSubscribersParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
	Q      *string `json:"q"`
}

type ListSubscribersRow struct {
	ID               uuid.UUID  `json:"id"`
	TenantID         uuid.UUID  `json:"tenant_id"`
	LocationID       *uuid.UUID `json:"location_id"`
	FullName         string     `json:"full_name"`
	PhoneNumber      string     `json:"phone_number"`
	Email            *string    `json:"email"`
	PhysicalAddress  *string    `json:"physical_address"`
	PppoeUsername    string     `json:"pppoe_username"`
	PppoePasswordEnc []byte     `json:"pppoe_password_enc"`
	Status           string     `json:"status"`
	PlanID           *uuid.UUID `json:"plan_id"`
	NextRenewalAt    *time.Time `json:"next_renewal_at"`
	CreditCents      int32      `json:"credit_cents"`
	AutoRenew        bool       `json:"auto_renew"`
	ReminderStage    int32      `json:"reminder_stage"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	PlanName         *string    `json:"plan_name"`
	PlanPriceCents   *int32     `json:"plan_price_cents"`
	Online           bool       `json:"online"`
}

func (q *Queries) ListSubscribers(ctx context.Context, arg ListSubscribersParams) ([]ListSubscribersRow, error) {
	rows, err := q.db.Query(ctx, listSubscribers,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscribersRow{}
	for rows.Next() {
		var i ListSubscribersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LocationID,
			&i.FullName,
			&i.PhoneNumber,
			&i.Email,
			&i.PhysicalAddress,
			&i.PppoeUsername,
			&i.PppoePasswordEnc,
			&i.Status,
			&i.PlanID,
			&i.NextRenewalAt,
			&i.CreditCents,
			&i.AutoRenew,
			&i.ReminderStage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanName,
			&i.PlanPriceCents,
			&i.Online,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const onTimeRate = `-- name: OnTimeRate :one
SELECT count(*) FILTER (WHERE status = 'active')::int AS on_time, count(*) FILTER (WHERE status IN ('active', 'expired', 'suspended'))::int AS total
FROM subscribers
`

type OnTimeRateRow struct {
	OnTime int32 `json:"on_time"`
	Total  int32 `json:"total"`
}

func (q *Queries) OnTimeRate(ctx context.Context) (OnTimeRateRow, error) {
	row := q.db.QueryRow(ctx, onTimeRate)
	var i OnTimeRateRow
	err := row.Scan(&i.OnTime, &i.Total)
	return i, err
}

const setReminderStage = `-- name: SetReminderStage :exec
UPDATE subscribers SET reminder_stage = $2 WHERE id = $1
`

type SetReminderStageParams struct {
	ID            uuid.UUID `json:"id"`
	ReminderStage int32     `json:"reminder_stage"`
}

func (q *Queries) SetReminderStage(ctx context.Context, arg SetReminderStageParams) error {
	_, err := q.db.Exec(ctx, setReminderStage, arg.ID, arg.ReminderStage)
	return err
}

const setSubscriberPassword = `-- name: SetSubscriberPassword :exec
UPDATE subscribers SET pppoe_password_enc = $2, updated_at = NOW() WHERE id = $1
`

type SetSubscriberPasswordParams struct {
	ID               uuid.UUID `json:"id"`
	PppoePasswordEnc []byte    `json:"pppoe_password_enc"`
}

func (q *Queries) SetSubscriberPassword(ctx context.Context, arg SetSubscriberPasswordParams) error {
	_, err := q.db.Exec(ctx, setSubscriberPassword, arg.ID, arg.PppoePasswordEnc)
	return err
}

const setSubscriberStatus = `-- name: SetSubscriberStatus :exec
UPDATE subscribers SET status = $2, updated_at = NOW() WHERE id = $1
`

type SetSubscriberStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetSubscriberStatus(ctx context.Context, arg SetSubscriberStatusParams) error {
	_, err := q.db.Exec(ctx, setSubscriberStatus, arg.ID, arg.Status)
	return err
}

const updateSubscriber = `-- name: UpdateSubscriber :one
UPDATE subscribers SET full_name = $2, phone_number = $3, email = $4, physical_address = $5, location_id = $6,
    plan_id = $7, auto_renew = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, location_id, full_name, phone_number, email, physical_address, pppoe_username, pppoe_password_enc, status, plan_id, next_renewal_at, credit_cents, auto_renew, reminder_stage, created_at, updated_at
`

type UpdateSubscriberParams struct {
	ID              uuid.UUID  `json:"id"`
	FullName        string     `json:"full_name"`
	PhoneNumber     string     `json:"phone_number"`
	Email           *string    `json:"email"`
	PhysicalAddress *string    `json:"physical_address"`
	LocationID      *uuid.UUID `json:"location_id"`
	PlanID          *uuid.UUID `json:"plan_id"`
	AutoRenew       bool       `json:"auto_renew"`
}

func (q *Queries) UpdateSubscriber(ctx context.Context, arg UpdateSubscriberParams) (Subscriber, error) {
	row := q.db.QueryRow(ctx, updateSubscriber,
		arg.ID,
		arg.FullName,
		arg.PhoneNumber,
		arg.Email,
		arg.PhysicalAddress,
		arg.LocationID,
		arg.PlanID,
		arg.AutoRenew,
	)
	var i Subscriber
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LocationID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.PhysicalAddress,
		&i.PppoeUsername,
		&i.PppoePasswordEnc,
		&i.Status,
		&i.PlanID,
		&i.NextRenewalAt,
		&i.CreditCents,
		&i.AutoRenew,
		&i.ReminderStage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
