// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tenants.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeTenantIDs = `-- name: ActiveTenantIDs :many
SELECT active_tenant_ids()::uuid AS tenant_id
`

func (q *Queries) ActiveTenantIDs(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, activeTenantIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var tenant_id uuid.UUID
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addSMSCredits = `-- name: AddSMSCredits :one
UPDATE tenants SET sms_credits = sms_credits + $1::int WHERE id = app_tenant() RETURNING sms_credits
`

func (q *Queries) AddSMSCredits(ctx context.Context, credits int32) (int32, error) {
	row := q.db.QueryRow(ctx, addSMSCredits, credits)
	var sms_credits int32
	err := row.Scan(&sms_credits)
	return sms_credits, err
}

const authSessionTenant = `-- name: AuthSessionTenant :one
SELECT auth_session_tenant($1::bytea)::uuid AS tenant_id
`

func (q *Queries) AuthSessionTenant(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, authSessionTenant, tokenHash)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth_sessions (token_hash, tenant_id, expires_at) VALUES ($1, app_tenant(), $2)
`

type CreateAuthSessionParams struct {
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, email, password_hash, name, slug, account_prefix, callback_token, dek_wrapped,
                     support_phone, mpesa_shortcode_type, mpesa_shortcode)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, email, password_hash, name, slug, account_prefix, next_account_no, plan, mpesa_mode, mpesa_shortcode_type, mpesa_shortcode, mpesa_store_number, mpesa_credentials_enc, mpesa_env, callback_token, dek_wrapped, sms_credits, sms_sender, reminder_sms_enabled, hotspot_expiry_sms_enabled, hotspot_expiry_sms_template, support_phone, subscription_status, trial_ends_at, subscription_expires_at, grace_hours, portal_domain, logo_url, primary_color, timezone, created_at, updated_at
`

type CreateTenantParams struct {
	ID                 uuid.UUID `json:"id"`
	Email              string    `json:"email"`
	PasswordHash       string    `json:"password_hash"`
	Name               string    `json:"name"`
	Slug               string    `json:"slug"`
	AccountPrefix      string    `json:"account_prefix"`
	CallbackToken      string    `json:"callback_token"`
	DekWrapped         []byte    `json:"dek_wrapped"`
	SupportPhone       *string   `json:"support_phone"`
	MpesaShortcodeType string    `json:"mpesa_shortcode_type"`
	MpesaShortcode     *string   `json:"mpesa_shortcode"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Slug,
		arg.AccountPrefix,
		arg.CallbackToken,
		arg.DekWrapped,
		arg.SupportPhone,
		arg.MpesaShortcodeType,
		arg.MpesaShortcode,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Slug,
		&i.AccountPrefix,
		&i.NextAccountNo,
		&i.Plan,
		&i.MpesaMode,
		&i.MpesaShortcodeType,
		&i.MpesaShortcode,
		&i.MpesaStoreNumber,
		&i.MpesaCredentialsEnc,
		&i.MpesaEnv,
		&i.CallbackToken,
		&i.DekWrapped,
		&i.SmsCredits,
		&i.SmsSender,
		&i.ReminderSmsEnabled,
		&i.HotspotExpirySmsEnabled,
		&i.HotspotExpirySmsTemplate,
		&i.SupportPhone,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.SubscriptionExpiresAt,
		&i.GraceHours,
		&i.PortalDomain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthSession = `-- name: DeleteAuthSession :exec
DELETE FROM auth_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteAuthSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteAuthSession, tokenHash)
	return err
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :exec
DELETE FROM auth_sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthSessions)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT id, email, password_hash, name, slug, account_prefix, next_account_no, plan, mpesa_mode, mpesa_shortcode_type, mpesa_shortcode, mpesa_store_number, mpesa_credentials_enc, mpesa_env, callback_token, dek_wrapped, sms_credits, sms_sender, reminder_sms_enabled, hotspot_expiry_sms_enabled, hotspot_expiry_sms_template, support_phone, subscription_status, trial_ends_at, subscription_expires_at, grace_hours, portal_domain, logo_url, primary_color, timezone, created_at, updated_at FROM tenants WHERE id = app_tenant()
`

func (q *Queries) GetTenant(ctx context.Context) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Slug,
		&i.AccountPrefix,
		&i.NextAccountNo,
		&i.Plan,
		&i.MpesaMode,
		&i.MpesaShortcodeType,
		&i.MpesaShortcode,
		&i.MpesaStoreNumber,
		&i.MpesaCredentialsEnc,
		&i.MpesaEnv,
		&i.CallbackToken,
		&i.DekWrapped,
		&i.SmsCredits,
		&i.SmsSender,
		&i.ReminderSmsEnabled,
		&i.HotspotExpirySmsEnabled,
		&i.HotspotExpirySmsTemplate,
		&i.SupportPhone,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.SubscriptionExpiresAt,
		&i.GraceHours,
		&i.PortalDomain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextAccountNumber = `-- name: NextAccountNumber :one
UPDATE tenants SET next_account_no = next_account_no + 1
WHERE id = app_tenant()
RETURNING account_prefix, (next_account_no - 1)::int AS account_no
`

type NextAccountNumberRow struct {
	AccountPrefix string `json:"account_prefix"`
	AccountNo     int32  `json:"account_no"`
}

func (q *Queries) NextAccountNumber(ctx context.Context) (NextAccountNumberRow, error) {
	row := q.db.QueryRow(ctx, nextAccountNumber)
	var i NextAccountNumberRow
	err := row.Scan(&i.AccountPrefix, &i.AccountNo)
	return i, err
}

const setSubscription = `-- name: SetSubscription :exec
UPDATE tenants SET subscription_status = $1, subscription_expires_at = $2, updated_at = NOW() WHERE id = app_tenant()
`

type SetSubscriptionParams struct {
	SubscriptionStatus    string     `json:"subscription_status"`
	SubscriptionExpiresAt *time.Time `json:"subscription_expires_at"`
}

func (q *Queries) SetSubscription(ctx context.Context, arg SetSubscriptionParams) error {
	_, err := q.db.Exec(ctx, setSubscription, arg.SubscriptionStatus, arg.SubscriptionExpiresAt)
	return err
}

const setTenantAccountPrefix = `-- name: SetTenantAccountPrefix :exec
UPDATE tenants SET account_prefix = $1, updated_at = NOW() WHERE id = app_tenant()
`

func (q *Queries) SetTenantAccountPrefix(ctx context.Context, accountPrefix string) error {
	_, err := q.db.Exec(ctx, setTenantAccountPrefix, accountPrefix)
	return err
}

const setTenantMpesaCredentials = `-- name: SetTenantMpesaCredentials :exec
UPDATE tenants SET mpesa_credentials_enc = $1, updated_at = NOW() WHERE id = app_tenant()
`

func (q *Queries) SetTenantMpesaCredentials(ctx context.Context, mpesaCredentialsEnc []byte) error {
	_, err := q.db.Exec(ctx, setTenantMpesaCredentials, mpesaCredentialsEnc)
	return err
}

const setTenantPassword = `-- name: SetTenantPassword :exec
UPDATE tenants SET password_hash = $1, updated_at = NOW() WHERE id = app_tenant()
`

func (q *Queries) SetTenantPassword(ctx context.Context, passwordHash string) error {
	_, err := q.db.Exec(ctx, setTenantPassword, passwordHash)
	return err
}

const takeSMSCredits = `-- name: TakeSMSCredits :one
UPDATE tenants SET sms_credits = sms_credits - $1::int
WHERE id = app_tenant() AND sms_credits >= $1::int
RETURNING sms_credits
`

func (q *Queries) TakeSMSCredits(ctx context.Context, credits int32) (int32, error) {
	row := q.db.QueryRow(ctx, takeSMSCredits, credits)
	var sms_credits int32
	err := row.Scan(&sms_credits)
	return sms_credits, err
}

const tenantByPortalDomain = `-- name: TenantByPortalDomain :one
SELECT tenant_by_portal_domain($1::text)::uuid AS tenant_id
`

func (q *Queries) TenantByPortalDomain(ctx context.Context, domain string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, tenantByPortalDomain, domain)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const tenantBySlug = `-- name: TenantBySlug :one
SELECT t.tenant_id::uuid AS tenant_id, t.callback_token::text AS callback_token FROM tenant_by_slug($1::text) t
`

type TenantBySlugRow struct {
	TenantID      uuid.UUID `json:"tenant_id"`
	CallbackToken string    `json:"callback_token"`
}

func (q *Queries) TenantBySlug(ctx context.Context, slug string) (TenantBySlugRow, error) {
	row := q.db.QueryRow(ctx, tenantBySlug, slug)
	var i TenantBySlugRow
	err := row.Scan(&i.TenantID, &i.CallbackToken)
	return i, err
}

const tenantIdentityTaken = `-- name: TenantIdentityTaken :one
SELECT t.email_taken::bool AS email_taken, t.slug_taken::bool AS slug_taken, t.prefix_taken::bool AS prefix_taken FROM tenant_identity_taken($1::text, $2::text, $3::text) t
`

type TenantIdentityTakenParams struct {
	Email  string `json:"email"`
	Slug   string `json:"slug"`
	Prefix string `json:"prefix"`
}

type TenantIdentityTakenRow struct {
	EmailTaken  bool `json:"email_taken"`
	SlugTaken   bool `json:"slug_taken"`
	PrefixTaken bool `json:"prefix_taken"`
}

func (q *Queries) TenantIdentityTaken(ctx context.Context, arg TenantIdentityTakenParams) (TenantIdentityTakenRow, error) {
	row := q.db.QueryRow(ctx, tenantIdentityTaken, arg.Email, arg.Slug, arg.Prefix)
	var i TenantIdentityTakenRow
	err := row.Scan(&i.EmailTaken, &i.SlugTaken, &i.PrefixTaken)
	return i, err
}

const tenantLogin = `-- name: TenantLogin :one
SELECT t.tenant_id::uuid AS tenant_id, t.password_hash::text AS password_hash FROM tenant_login($1::text) t
`

type TenantLoginRow struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) TenantLogin(ctx context.Context, email string) (TenantLoginRow, error) {
	row := q.db.QueryRow(ctx, tenantLogin, email)
	var i TenantLoginRow
	err := row.Scan(&i.TenantID, &i.PasswordHash)
	return i, err
}

const updateTenantSettings = `-- name: UpdateTenantSettings :one
UPDATE tenants SET
    name = $1,
    support_phone = $2,
    mpesa_mode = $3,
    mpesa_shortcode_type = $4,
    mpesa_shortcode = $5,
    mpesa_store_number = $6,
    mpesa_env = $7,
    primary_color = $8,
    logo_url = $9,
    portal_domain = $10,
    grace_hours = $11,
    reminder_sms_enabled = $12,
    hotspot_expiry_sms_enabled = $13,
    hotspot_expiry_sms_template = $14,
    sms_sender = $15,
    timezone = $16,
    updated_at = NOW()
WHERE id = app_tenant()
RETURNING id, email, password_hash, name, slug, account_prefix, next_account_no, plan, mpesa_mode, mpesa_shortcode_type, mpesa_shortcode, mpesa_store_number, mpesa_credentials_enc, mpesa_env, callback_token, dek_wrapped, sms_credits, sms_sender, reminder_sms_enabled, hotspot_expiry_sms_enabled, hotspot_expiry_sms_template, support_phone, subscription_status, trial_ends_at, subscription_expires_at, grace_hours, portal_domain, logo_url, primary_color, timezone, created_at, updated_at
`

type UpdateTenantSettingsParams struct {
	Name                     string  `json:"name"`
	SupportPhone             *string `json:"support_phone"`
	MpesaMode                string  `json:"mpesa_mode"`
	MpesaShortcodeType       string  `json:"mpesa_shortcode_type"`
	MpesaShortcode           *string `json:"mpesa_shortcode"`
	MpesaStoreNumber         *string `json:"mpesa_store_number"`
	MpesaEnv                 string  `json:"mpesa_env"`
	PrimaryColor             string  `json:"primary_color"`
	LogoUrl                  *string `json:"logo_url"`
	PortalDomain             *string `json:"portal_domain"`
	GraceHours               int32   `json:"grace_hours"`
	ReminderSmsEnabled       bool    `json:"reminder_sms_enabled"`
	HotspotExpirySmsEnabled  bool    `json:"hotspot_expiry_sms_enabled"`
	HotspotExpirySmsTemplate *string `json:"hotspot_expiry_sms_template"`
	SmsSender                *string `json:"sms_sender"`
	Timezone                 string  `json:"timezone"`
}

func (q *Queries) UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantSettings,
		arg.Name,
		arg.SupportPhone,
		arg.MpesaMode,
		arg.MpesaShortcodeType,
		arg.MpesaShortcode,
		arg.MpesaStoreNumber,
		arg.MpesaEnv,
		arg.PrimaryColor,
		arg.LogoUrl,
		arg.PortalDomain,
		arg.GraceHours,
		arg.ReminderSmsEnabled,
		arg.HotspotExpirySmsEnabled,
		arg.HotspotExpirySmsTemplate,
		arg.SmsSender,
		arg.Timezone,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Slug,
		&i.AccountPrefix,
		&i.NextAccountNo,
		&i.Plan,
		&i.MpesaMode,
		&i.MpesaShortcodeType,
		&i.MpesaShortcode,
		&i.MpesaStoreNumber,
		&i.MpesaCredentialsEnc,
		&i.MpesaEnv,
		&i.CallbackToken,
		&i.DekWrapped,
		&i.SmsCredits,
		&i.SmsSender,
		&i.ReminderSmsEnabled,
		&i.HotspotExpirySmsEnabled,
		&i.HotspotExpirySmsTemplate,
		&i.SupportPhone,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.SubscriptionExpiresAt,
		&i.GraceHours,
		&i.PortalDomain,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
